// Complete UI translations for the languages that were previously partial.
// Official product, institution, qualification, and technology names remain unchanged.
const extendedTranslations = {
  "zh-CN": {
    "nav.about":"关于我","nav.career":"经历","nav.skills":"技能","nav.certifications":"资格与学习经历","nav.featured":"项目","nav.otherProjects":"其他项目","nav.github":"GitHub","nav.contact":"联系","language.label":"语言","language.full":"完整翻译","language.partial":"完整翻译",
    "hero.eyebrow":"多语言Web开发者","hero.line1":"静态网站。","hero.line2":"AI辅助工作流程。","hero.line3":"多语言产品。","hero.copy":"设计并开发连接日本、台湾与亚洲的实用数字产品。","hero.projects":"查看项目","hero.tagsLabel":"核心技术","hero.statCommercial":"商业网站项目・未税","hero.statFounded":"创立SLEEP LATE LAB","hero.statRemote":"远程合作",
    "section.about":"关于我","section.career":"教育、实务与学习经历","section.skills":"技能","section.certifications":"资格、认证与学习经历","section.featured":"精选项目","section.otherProjects":"其他项目","section.contact":"联系",
    "about.lead":"主要在日本与台湾从事多语言网站开发和个人产品开发。","about.body":"结合在多个国家学习的经验，从企划、信息架构、实现到发布均可独立负责。重点包括静态网站、WordPress、前端开发、API集成与SEO，并将摄影、视频和文案经验用于网站表现与用户体验。","about.focusLabel":"重点","about.focus":"Web开发、WordPress、个人开发","about.locationLabel":"地区","about.location":"日本 / 台湾・远程","about.languagesLabel":"语言","about.languages":"日语、英语、中文、泰语","about.creative":"将摄影、视频和文案经验用于Web信息架构与视觉表达。","about.personalWork":"个人作品 → koshijpn.com",
    "career.education":"教育经历","career.international":"国际学习经历","career.2013a":"完成University of the Visayas ESL课程","career.2013b":"毕业于飞鸟未来高等学校","career.2018":"完成中国文化大学华语中心课程","career.2020b":"完成清迈大学泰语与文化课程","career.2020c":"完成Web Courses Bangkok网页专业与摄影课程","career.2021":"创立SLEEP LATE LAB","career.2022b":"完成Seoul Korean Language Academy Level A2","career.2023a":"完成NEXT Academy全栈Web开发课程","career.2024":"毕业于大手前大学，取得学术学士／心理学主修","career.viewAll":"查看全部教育、国际学习与资格 →",
    "projects.intro":"依据实用性、完成度与技术特点选出的代表项目。","project.purpose":"目的","project.role":"负责范围","project.tech":"使用技术","project.result":"成果","project.currentState":"状态","project.repositories":"代码仓库","project.year":"制作年份","project.noDescription":"请在公开仓库查看代码与实现细节。","projects.apiFallback":"目前无法连接GitHub，正在显示本地保存的公开项目列表。","status.public":"公开","content.caseStudy":"案例研究",
    "skills.alsoWorking":"也使用：","skills.creativeBackground":"创意背景：","certifications.intro":"整理资格、认证、获奖与已完成课程；不公开证明文件链接。",
    "commercial.eyebrow":"精选商业实绩","commercial.title":"企业网站","commercial.visibility":"客户名称不公开","commercial.value":"项目规模","commercial.delivery":"交付范围","commercial.scope":"企划、制作与发布","commercial.tagPlanning":"企划","commercial.tagResponsive":"响应式设计",
    "github.loading":"正在加载GitHub公开数据…","github.publicRepos":"公开仓库","github.languages":"主要语言","github.latestActivity":"最新公开仓库更新","github.lastSynced":"最后同步","github.recent":"最近更新","github.fallback":"暂时无法取得GitHub公开数据；请前往GitHub个人资料查看最新信息。","github.lead":"源代码、实验与持续开发内容均在GitHub管理。","github.body":"可在公开仓库查看实现细节、项目结构与开发记录。","github.cta":"查看GitHub个人资料",
    "contact.lead":"一起打造实用的产品。","contact.body":"技术交流、共同开发与公开代码请前往GitHub；网站制作与商业项目请联系SLEEP LATE LAB。","contact.githubCta":"查看GitHub","contact.commercialCta":"咨询商业项目","contact.replyLabel":"回复时间","contact.reply":"通常2至3个工作日内","contact.modeLabel":"合作方式","contact.mode":"远程合作","contact.regionLabel":"服务地区","contact.region":"日本・台湾・全球",
    "details.projectsTitle":"项目详情","details.projectsIntro":"收录客户网站、WordPress、静态网站、API、Private项目与公开仓库等开发实绩。","details.publicOnly":"其他公开仓库由GitHub API加载；商业项目请联系SLEEP LATE LAB。","details.profileTitle":"教育、国际学习与资格","details.profileIntro":"从首页移出的详细教育与学习记录；不公开证明文件链接。",
    "a11y.skip":"跳到主要内容","a11y.home":"Koshi作品集首页","a11y.openMenu":"打开菜单","a11y.navigation":"主导航","a11y.logoAlt":"Koshi标志","a11y.scrollProjects":"前往精选项目","a11y.portraitAlt":"菅原鸿志的个人照片","a11y.backTop":"返回页面顶部"
  },
  ko: {
    "nav.about":"소개","nav.career":"경력","nav.skills":"기술","nav.certifications":"자격 및 학습","nav.featured":"프로젝트","nav.otherProjects":"기타 프로젝트","nav.github":"GitHub","nav.contact":"문의","language.label":"언어","language.full":"전체 번역","language.partial":"전체 번역",
    "hero.eyebrow":"다국어 웹 개발자","hero.line1":"정적 웹사이트.","hero.line2":"AI 지원 워크플로.","hero.line3":"다국어 제품.","hero.copy":"일본·대만·아시아를 연결하는 실용적인 디지털 제품을 설계하고 개발합니다.","hero.projects":"프로젝트 보기","hero.tagsLabel":"핵심 기술","hero.statCommercial":"상업용 웹 프로젝트・세전","hero.statFounded":"SLEEP LATE LAB 설립","hero.statRemote":"원격 협업",
    "section.about":"소개","section.career":"교육·실무·학습 경험","section.skills":"기술","section.certifications":"자격·인증·학습 경험","section.featured":"주요 프로젝트","section.otherProjects":"기타 프로젝트","section.contact":"문의",
    "about.lead":"일본과 대만을 중심으로 다국어 웹 개발과 개인 제품 개발을 하고 있습니다.","about.body":"여러 나라에서 공부한 경험을 바탕으로 기획, 정보 설계, 구현, 공개까지 일관되게 담당합니다. 정적 사이트, WordPress, 프런트엔드, API 연동, SEO를 중심으로 하며 사진·영상·카피라이팅 경험을 웹 표현과 사용자 경험에 활용합니다.","about.focusLabel":"중점 분야","about.focus":"웹 개발, WordPress, 개인 개발","about.locationLabel":"지역","about.location":"일본 / 대만·원격","about.languagesLabel":"언어","about.languages":"일본어, 영어, 중국어, 태국어","about.creative":"사진, 영상, 카피라이팅 경험을 웹 정보 설계와 시각 표현에 활용합니다.","about.personalWork":"개인 작품 → koshijpn.com",
    "career.education":"학력","career.international":"국제 학습 경험","career.2013a":"University of the Visayas ESL 프로그램 수료","career.2013b":"아스카 미라이 고등학교 졸업","career.2018":"중국문화대학교 중국어센터 과정 수료","career.2020b":"치앙마이대학교 태국어·문화 프로그램 수료","career.2020c":"Web Courses Bangkok 웹 전문·사진 과정 수료","career.2021":"SLEEP LATE LAB 설립","career.2022b":"Seoul Korean Language Academy Level A2 수료","career.2023a":"NEXT Academy 풀스택 웹 개발 과정 수료","career.2024":"오테마에대학교 졸업, 학술학사·심리학 전공","career.viewAll":"전체 학력·국제 학습·자격 보기 →",
    "projects.intro":"실용성, 완성도, 기술적 특징을 기준으로 선정한 대표 프로젝트입니다.","project.purpose":"목적","project.role":"담당","project.tech":"사용 기술","project.result":"성과","project.currentState":"상태","project.repositories":"저장소","project.year":"제작 연도","project.noDescription":"공개 저장소에서 코드와 구현 세부 정보를 확인할 수 있습니다.","projects.apiFallback":"GitHub에 연결할 수 없어 로컬에 저장된 공개 프로젝트를 표시합니다.","status.public":"공개","content.caseStudy":"사례 연구",
    "skills.alsoWorking":"추가 사용 기술:","skills.creativeBackground":"크리에이티브 경험:","certifications.intro":"자격, 인증, 수상 및 수료 과정을 정리했습니다. 증명서 링크는 공개하지 않습니다.",
    "commercial.eyebrow":"주요 상업 프로젝트","commercial.title":"기업 웹사이트","commercial.visibility":"고객명 비공개","commercial.value":"프로젝트 규모","commercial.delivery":"담당 범위","commercial.scope":"기획·제작·공개","commercial.tagPlanning":"기획","commercial.tagResponsive":"반응형 디자인",
    "github.loading":"GitHub 공개 데이터를 불러오는 중…","github.publicRepos":"공개 저장소","github.languages":"주요 언어","github.latestActivity":"최근 공개 저장소 업데이트","github.lastSynced":"마지막 동기화","github.recent":"최근 업데이트","github.fallback":"GitHub 공개 데이터를 일시적으로 가져올 수 없습니다. 최신 정보는 GitHub 프로필에서 확인하세요.","github.lead":"소스 코드, 실험 및 진행 중인 개발을 GitHub에서 관리합니다.","github.body":"공개 저장소에서 구현 세부 정보, 프로젝트 구조, 개발 기록을 확인할 수 있습니다.","github.cta":"GitHub 프로필 보기",
    "contact.lead":"함께 유용한 것을 만들어 보세요.","contact.body":"기술 교류, 공동 개발, 공개 코드는 GitHub에서 확인해 주세요. 웹 제작과 상업 프로젝트는 SLEEP LATE LAB으로 문의해 주세요.","contact.githubCta":"GitHub 보기","contact.commercialCta":"상업 프로젝트 문의","contact.replyLabel":"답변 예상","contact.reply":"보통 영업일 기준 2~3일 이내","contact.modeLabel":"협업 방식","contact.mode":"원격 협업","contact.regionLabel":"대응 지역","contact.region":"일본·대만·전 세계",
    "details.projectsTitle":"프로젝트 상세","details.projectsIntro":"고객 웹사이트, WordPress, 정적 사이트, API, 비공개 프로젝트와 공개 저장소를 포함한 개발 실적입니다.","details.publicOnly":"추가 공개 저장소는 GitHub API에서 불러옵니다. 상업 프로젝트 문의는 SLEEP LATE LAB에서 받습니다.","details.profileTitle":"학력·국제 학습·자격","details.profileIntro":"홈에서 분리한 상세 학력과 학습 기록입니다. 증명서 링크는 공개하지 않습니다.",
    "a11y.skip":"본문으로 이동","a11y.home":"Koshi 포트폴리오 홈","a11y.openMenu":"메뉴 열기","a11y.navigation":"주요 내비게이션","a11y.logoAlt":"Koshi 로고","a11y.scrollProjects":"주요 프로젝트로 이동","a11y.portraitAlt":"Koshi Sugawara 프로필 사진","a11y.backTop":"페이지 위로"
  },
  th: {
    "nav.about":"เกี่ยวกับ","nav.career":"ประสบการณ์","nav.skills":"ทักษะ","nav.certifications":"คุณวุฒิและการเรียนรู้","nav.featured":"โปรเจกต์","nav.otherProjects":"โปรเจกต์อื่น","nav.github":"GitHub","nav.contact":"ติดต่อ","language.label":"ภาษา","language.full":"แปลครบถ้วน","language.partial":"แปลครบถ้วน",
    "hero.eyebrow":"นักพัฒนาเว็บหลายภาษา","hero.line1":"เว็บไซต์แบบสแตติก","hero.line2":"เวิร์กโฟลว์ที่ใช้ AI ช่วย","hero.line3":"ผลิตภัณฑ์หลายภาษา","hero.copy":"ออกแบบและพัฒนาผลิตภัณฑ์ดิจิทัลที่ใช้งานได้จริง เชื่อมโยงญี่ปุ่น ไต้หวัน และเอเชีย","hero.projects":"ดูโปรเจกต์","hero.tagsLabel":"เทคโนโลยีหลัก","hero.statCommercial":"โครงการเว็บเชิงพาณิชย์・ก่อนภาษี","hero.statFounded":"ก่อตั้ง SLEEP LATE LAB","hero.statRemote":"ทำงานทางไกล",
    "section.about":"เกี่ยวกับ","section.career":"การศึกษา ประสบการณ์ และการเรียนรู้","section.skills":"ทักษะ","section.certifications":"คุณวุฒิ การรับรอง และการเรียนรู้","section.featured":"โปรเจกต์เด่น","section.otherProjects":"โปรเจกต์อื่น","section.contact":"ติดต่อ",
    "about.lead":"ทำงานด้านการพัฒนาเว็บหลายภาษาและผลิตภัณฑ์ส่วนตัว โดยมีฐานหลักในญี่ปุ่นและไต้หวัน","about.body":"นำประสบการณ์การศึกษาในหลายประเทศมาใช้ดูแลตั้งแต่การวางแผน โครงสร้างข้อมูล การพัฒนา จนถึงการเผยแพร่ เน้นเว็บไซต์สแตติก WordPress ฟรอนต์เอนด์ การเชื่อมต่อ API และ SEO พร้อมนำประสบการณ์ด้านภาพถ่าย วิดีโอ และงานเขียนมาเสริมการนำเสนอและประสบการณ์ผู้ใช้","about.focusLabel":"จุดเน้น","about.focus":"พัฒนาเว็บ WordPress และผลิตภัณฑ์ส่วนตัว","about.locationLabel":"พื้นที่","about.location":"ญี่ปุ่น / ไต้หวัน・รีโมต","about.languagesLabel":"ภาษา","about.languages":"ญี่ปุ่น อังกฤษ จีน ไทย","about.creative":"นำประสบการณ์ภาพถ่าย วิดีโอ และการเขียนมาใช้กับโครงสร้างข้อมูลและภาพลักษณ์ของเว็บ","about.personalWork":"ผลงานส่วนตัว → koshijpn.com",
    "career.education":"การศึกษา","career.international":"การเรียนรู้ระดับนานาชาติ","career.2013a":"จบหลักสูตร ESL ที่ University of the Visayas","career.2013b":"จบจากโรงเรียนมัธยม Asuka Mirai","career.2018":"จบหลักสูตรภาษาจีนที่ Chinese Culture University","career.2020b":"จบหลักสูตรภาษาและวัฒนธรรมไทย มหาวิทยาลัยเชียงใหม่","career.2020c":"จบหลักสูตร Web Professional และ Photography ที่ Web Courses Bangkok","career.2021":"ก่อตั้ง SLEEP LATE LAB","career.2022b":"จบ Seoul Korean Language Academy Level A2","career.2023a":"จบหลักสูตร Full-Stack Web Development ที่ NEXT Academy","career.2024":"จบมหาวิทยาลัย Otemae ปริญญาตรีสาขาจิตวิทยา","career.viewAll":"ดูการศึกษา การเรียนรู้นานาชาติ และคุณวุฒิทั้งหมด →",
    "projects.intro":"โปรเจกต์ตัวแทนที่คัดเลือกจากประโยชน์ใช้สอย ความสมบูรณ์ และลักษณะทางเทคนิค","project.purpose":"เป้าหมาย","project.role":"หน้าที่","project.tech":"เทคโนโลยี","project.result":"ผลลัพธ์","project.currentState":"สถานะ","project.repositories":"รีโพซิทอรี","project.year":"ปีที่สร้าง","project.noDescription":"ดูโค้ดและรายละเอียดการพัฒนาได้ในรีโพซิทอรีสาธารณะ","projects.apiFallback":"ไม่สามารถเชื่อมต่อ GitHub จึงแสดงรายการโปรเจกต์สาธารณะที่บันทึกไว้ในเครื่อง","status.public":"สาธารณะ","content.caseStudy":"กรณีศึกษา",
    "skills.alsoWorking":"ใช้งานเพิ่มเติม:","skills.creativeBackground":"พื้นฐานงานสร้างสรรค์:","certifications.intro":"รวมคุณวุฒิ การรับรอง รางวัล และหลักสูตรที่จบแล้ว โดยไม่เผยแพร่ลิงก์เอกสารรับรอง",
    "commercial.eyebrow":"ผลงานเชิงพาณิชย์ที่เลือก","commercial.title":"เว็บไซต์บริษัท","commercial.visibility":"ไม่เปิดเผยชื่อลูกค้า","commercial.value":"มูลค่าโครงการ","commercial.delivery":"ขอบเขตงาน","commercial.scope":"วางแผน ผลิต และเผยแพร่","commercial.tagPlanning":"วางแผน","commercial.tagResponsive":"ออกแบบ Responsive",
    "github.loading":"กำลังโหลดข้อมูลสาธารณะจาก GitHub…","github.publicRepos":"รีโพซิทอรีสาธารณะ","github.languages":"ภาษาหลัก","github.latestActivity":"อัปเดตรีโพซิทอรีสาธารณะล่าสุด","github.lastSynced":"ซิงค์ล่าสุด","github.recent":"อัปเดตล่าสุด","github.fallback":"ไม่สามารถดึงข้อมูลสาธารณะจาก GitHub ได้ชั่วคราว โปรดดูข้อมูลล่าสุดในโปรไฟล์ GitHub","github.lead":"จัดการซอร์สโค้ด การทดลอง และงานพัฒนาต่อเนื่องบน GitHub","github.body":"ดูรายละเอียดการพัฒนา โครงสร้างโปรเจกต์ และประวัติการพัฒนาได้ในรีโพซิทอรีสาธารณะ","github.cta":"ดูโปรไฟล์ GitHub",
    "contact.lead":"มาสร้างสิ่งที่มีประโยชน์ร่วมกัน","contact.body":"สำหรับการแลกเปลี่ยนทางเทคนิค การพัฒนาร่วม และโค้ดสาธารณะ โปรดไปที่ GitHub ส่วนงานเว็บไซต์และโครงการเชิงพาณิชย์ โปรดติดต่อ SLEEP LATE LAB","contact.githubCta":"ดู GitHub","contact.commercialCta":"ปรึกษาโครงการเชิงพาณิชย์","contact.replyLabel":"เวลาตอบกลับ","contact.reply":"โดยปกติภายใน 2–3 วันทำการ","contact.modeLabel":"รูปแบบการทำงาน","contact.mode":"ทำงานทางไกล","contact.regionLabel":"พื้นที่ให้บริการ","contact.region":"ญี่ปุ่น・ไต้หวัน・ทั่วโลก",
    "details.projectsTitle":"รายละเอียดโปรเจกต์","details.projectsIntro":"ผลงานพัฒนาที่รวมเว็บไซต์ลูกค้า WordPress เว็บไซต์สแตติก API โปรเจกต์ส่วนตัว และรีโพซิทอรีสาธารณะ","details.publicOnly":"รีโพซิทอรีสาธารณะเพิ่มเติมโหลดจาก GitHub API และรับคำปรึกษาเชิงพาณิชย์ผ่าน SLEEP LATE LAB","details.profileTitle":"การศึกษา การเรียนรู้นานาชาติ และคุณวุฒิ","details.profileIntro":"ประวัติการศึกษาและการเรียนรู้แบบละเอียดที่แยกจากหน้าแรก โดยไม่เผยแพร่ลิงก์เอกสาร",
    "a11y.skip":"ไปยังเนื้อหาหลัก","a11y.home":"หน้าแรกพอร์ตโฟลิโอ Koshi","a11y.openMenu":"เปิดเมนู","a11y.navigation":"เมนูหลัก","a11y.logoAlt":"โลโก้ Koshi","a11y.scrollProjects":"ไปยังโปรเจกต์เด่น","a11y.portraitAlt":"ภาพบุคคลของ Koshi Sugawara","a11y.backTop":"กลับขึ้นด้านบน"
  },
  vi: {
    "nav.about":"Giới thiệu","nav.career":"Kinh nghiệm","nav.skills":"Kỹ năng","nav.certifications":"Chứng chỉ và học tập","nav.featured":"Dự án","nav.otherProjects":"Dự án khác","nav.github":"GitHub","nav.contact":"Liên hệ","language.label":"Ngôn ngữ","language.full":"Bản dịch đầy đủ","language.partial":"Bản dịch đầy đủ",
    "hero.eyebrow":"Lập trình viên web đa ngôn ngữ","hero.line1":"Website tĩnh.","hero.line2":"Quy trình có AI hỗ trợ.","hero.line3":"Sản phẩm đa ngôn ngữ.","hero.copy":"Thiết kế và phát triển sản phẩm số thiết thực kết nối Nhật Bản, Đài Loan và châu Á.","hero.projects":"Xem dự án","hero.tagsLabel":"Công nghệ chính","hero.statCommercial":"Dự án web thương mại・chưa thuế","hero.statFounded":"Thành lập SLEEP LATE LAB","hero.statRemote":"Hợp tác từ xa",
    "section.about":"Giới thiệu","section.career":"Học vấn, công việc và quá trình học tập","section.skills":"Kỹ năng","section.certifications":"Chứng chỉ, công nhận và học tập","section.featured":"Dự án nổi bật","section.otherProjects":"Dự án khác","section.contact":"Liên hệ",
    "about.lead":"Tôi tập trung vào phát triển web đa ngôn ngữ và sản phẩm cá nhân, chủ yếu tại Nhật Bản và Đài Loan.","about.body":"Tận dụng kinh nghiệm học tập ở nhiều quốc gia, tôi đảm nhiệm xuyên suốt từ lập kế hoạch, kiến trúc thông tin, triển khai đến xuất bản. Trọng tâm là website tĩnh, WordPress, front-end, tích hợp API và SEO; kinh nghiệm nhiếp ảnh, video và viết nội dung hỗ trợ cách thể hiện và trải nghiệm người dùng trên web.","about.focusLabel":"Trọng tâm","about.focus":"Phát triển web, WordPress, sản phẩm cá nhân","about.locationLabel":"Khu vực","about.location":"Nhật Bản / Đài Loan・từ xa","about.languagesLabel":"Ngôn ngữ","about.languages":"Tiếng Nhật, Anh, Trung, Thái","about.creative":"Kinh nghiệm nhiếp ảnh, video và viết nội dung được ứng dụng vào kiến trúc thông tin và thể hiện hình ảnh trên web.","about.personalWork":"Tác phẩm cá nhân → koshijpn.com",
    "career.education":"Học vấn","career.international":"Học tập quốc tế","career.2013a":"Hoàn thành chương trình ESL tại University of the Visayas","career.2013b":"Tốt nghiệp trường trung học Asuka Mirai","career.2018":"Hoàn thành chương trình tiếng Hoa tại Chinese Culture University","career.2020b":"Hoàn thành chương trình Ngôn ngữ và Văn hóa Thái tại Đại học Chiang Mai","career.2020c":"Hoàn thành khóa Web Professional và Photography tại Web Courses Bangkok","career.2021":"Thành lập SLEEP LATE LAB","career.2022b":"Hoàn thành Seoul Korean Language Academy Level A2","career.2023a":"Hoàn thành chương trình Full-Stack Web Development tại NEXT Academy","career.2024":"Tốt nghiệp Đại học Otemae, Cử nhân Nghệ thuật chuyên ngành Tâm lý học","career.viewAll":"Xem toàn bộ học vấn, học tập quốc tế và chứng chỉ →",
    "projects.intro":"Các dự án tiêu biểu được chọn theo tính thực tiễn, độ hoàn thiện và đặc điểm kỹ thuật.","project.purpose":"Mục tiêu","project.role":"Vai trò","project.tech":"Công nghệ","project.result":"Kết quả","project.currentState":"Trạng thái","project.repositories":"Kho mã","project.year":"Năm thực hiện","project.noDescription":"Xem mã nguồn và chi tiết triển khai trong kho công khai.","projects.apiFallback":"Không thể kết nối GitHub; đang hiển thị danh sách dự án công khai được lưu cục bộ.","status.public":"Công khai","content.caseStudy":"Nghiên cứu điển hình",
    "skills.alsoWorking":"Cũng sử dụng:","skills.creativeBackground":"Nền tảng sáng tạo:","certifications.intro":"Danh sách chứng chỉ, công nhận, giải thưởng và khóa học đã hoàn thành; không công khai liên kết giấy chứng nhận.",
    "commercial.eyebrow":"Dự án thương mại tiêu biểu","commercial.title":"Website doanh nghiệp","commercial.visibility":"Không công khai tên khách hàng","commercial.value":"Giá trị dự án","commercial.delivery":"Phạm vi bàn giao","commercial.scope":"Lập kế hoạch, sản xuất và xuất bản","commercial.tagPlanning":"Lập kế hoạch","commercial.tagResponsive":"Thiết kế đáp ứng",
    "github.loading":"Đang tải dữ liệu công khai từ GitHub…","github.publicRepos":"Kho công khai","github.languages":"Ngôn ngữ chính","github.latestActivity":"Cập nhật kho công khai mới nhất","github.lastSynced":"Đồng bộ lần cuối","github.recent":"Cập nhật gần đây","github.fallback":"Tạm thời không thể lấy dữ liệu công khai từ GitHub. Vui lòng xem thông tin mới nhất trên hồ sơ GitHub.","github.lead":"Mã nguồn, thử nghiệm và quá trình phát triển đang được quản lý trên GitHub.","github.body":"Các kho công khai cho phép xem chi tiết triển khai, cấu trúc dự án và lịch sử phát triển.","github.cta":"Xem hồ sơ GitHub",
    "contact.lead":"Hãy cùng tạo ra điều hữu ích.","contact.body":"Trao đổi kỹ thuật, cộng tác và mã công khai tại GitHub. Với website và dự án thương mại, vui lòng liên hệ SLEEP LATE LAB.","contact.githubCta":"Xem GitHub","contact.commercialCta":"Trao đổi dự án thương mại","contact.replyLabel":"Thời gian phản hồi","contact.reply":"Thường trong 2–3 ngày làm việc","contact.modeLabel":"Hình thức hợp tác","contact.mode":"Từ xa","contact.regionLabel":"Khu vực","contact.region":"Nhật Bản・Đài Loan・Toàn cầu",
    "details.projectsTitle":"Chi tiết dự án","details.projectsIntro":"Kinh nghiệm phát triển gồm website khách hàng, WordPress, website tĩnh, API, dự án riêng tư và kho công khai.","details.publicOnly":"Các kho công khai bổ sung được tải từ GitHub API; dự án thương mại được tiếp nhận qua SLEEP LATE LAB.","details.profileTitle":"Học vấn, học tập quốc tế và chứng chỉ","details.profileIntro":"Hồ sơ học vấn và học tập chi tiết được tách khỏi trang chủ; không công khai liên kết giấy chứng nhận.",
    "a11y.skip":"Chuyển đến nội dung chính","a11y.home":"Trang chủ portfolio Koshi","a11y.openMenu":"Mở menu","a11y.navigation":"Điều hướng chính","a11y.logoAlt":"Logo Koshi","a11y.scrollProjects":"Chuyển đến dự án nổi bật","a11y.portraitAlt":"Ảnh chân dung Koshi Sugawara","a11y.backTop":"Lên đầu trang"
  },
  es: {
    "nav.about":"Perfil","nav.career":"Experiencia","nav.skills":"Habilidades","nav.certifications":"Certificaciones y formación","nav.featured":"Proyectos","nav.otherProjects":"Otros proyectos","nav.github":"GitHub","nav.contact":"Contacto","language.label":"Idioma","language.full":"Traducción completa","language.partial":"Traducción completa",
    "hero.eyebrow":"Desarrollador web multilingüe","hero.line1":"Sitios web estáticos.","hero.line2":"Flujos asistidos por IA.","hero.line3":"Productos multilingües.","hero.copy":"Diseño y desarrollo productos digitales prácticos que conectan Japón, Taiwán y Asia.","hero.projects":"Ver proyectos","hero.tagsLabel":"Tecnologías principales","hero.statCommercial":"Proyecto web comercial・sin impuestos","hero.statFounded":"Fundación de SLEEP LATE LAB","hero.statRemote":"Colaboración remota",
    "section.about":"Perfil","section.career":"Educación, experiencia y formación","section.skills":"Habilidades","section.certifications":"Certificaciones, acreditaciones y formación","section.featured":"Proyectos destacados","section.otherProjects":"Otros proyectos","section.contact":"Contacto",
    "about.lead":"Trabajo principalmente entre Japón y Taiwán en desarrollo web multilingüe y productos independientes.","about.body":"A partir de mi experiencia estudiando en varios países, me encargo de la planificación, arquitectura de información, implementación y publicación. Me centro en sitios estáticos, WordPress, front-end, integración de API y SEO, y aplico mi experiencia en fotografía, vídeo y redacción a la expresión visual y experiencia de usuario en la web.","about.focusLabel":"Enfoque","about.focus":"Desarrollo web, WordPress y productos independientes","about.locationLabel":"Ubicación","about.location":"Japón / Taiwán・remoto","about.languagesLabel":"Idiomas","about.languages":"Japonés, inglés, chino y tailandés","about.creative":"La experiencia en fotografía, vídeo y redacción apoya la arquitectura de información y expresión visual de mis proyectos web.","about.personalWork":"Trabajo personal → koshijpn.com",
    "career.education":"Educación","career.international":"Formación internacional","career.2013a":"Programa ESL completado en University of the Visayas","career.2013b":"Graduado de Asuka Mirai High School","career.2018":"Programa de mandarín completado en Chinese Culture University","career.2020b":"Programa de lengua y cultura tailandesas completado en Chiang Mai University","career.2020c":"Cursos Web Professional y Photography completados en Web Courses Bangkok","career.2021":"Fundación de SLEEP LATE LAB","career.2022b":"Seoul Korean Language Academy Level A2 completado","career.2023a":"Programa Full-Stack Web Development completado en NEXT Academy","career.2024":"Graduado de Otemae University con licenciatura y especialización en Psicología","career.viewAll":"Ver toda la educación, formación internacional y certificaciones →",
    "projects.intro":"Proyectos representativos seleccionados por su utilidad, acabado y carácter técnico.","project.purpose":"Objetivo","project.role":"Responsabilidad","project.tech":"Tecnologías","project.result":"Resultado","project.currentState":"Estado","project.repositories":"Repositorios","project.year":"Año","project.noDescription":"Consulta el repositorio público para ver el código y los detalles de implementación.","projects.apiFallback":"No se pudo conectar con GitHub. Se muestra la lista local de proyectos públicos.","status.public":"Público","content.caseStudy":"Caso de estudio",
    "skills.alsoWorking":"También trabajo con:","skills.creativeBackground":"Experiencia creativa:","certifications.intro":"Certificaciones, acreditaciones, premios y cursos completados. No se publican enlaces a documentos acreditativos.",
    "commercial.eyebrow":"Trabajo comercial seleccionado","commercial.title":"Sitio web corporativo","commercial.visibility":"Nombre del cliente no publicado","commercial.value":"Valor del proyecto","commercial.delivery":"Alcance","commercial.scope":"Planificación, producción y publicación","commercial.tagPlanning":"Planificación","commercial.tagResponsive":"Diseño responsivo",
    "github.loading":"Cargando datos públicos de GitHub…","github.publicRepos":"Repositorios públicos","github.languages":"Lenguajes principales","github.latestActivity":"Última actualización de repositorio público","github.lastSynced":"Última sincronización","github.recent":"Actualizados recientemente","github.fallback":"Los datos públicos de GitHub no están disponibles temporalmente. Consulta la información actual en el perfil de GitHub.","github.lead":"El código fuente, los experimentos y el desarrollo continuo están disponibles en GitHub.","github.body":"Los repositorios públicos muestran detalles de implementación, estructura de proyectos e historial de desarrollo.","github.cta":"Ver perfil de GitHub",
    "contact.lead":"Construyamos algo útil juntos.","contact.body":"Para conversaciones técnicas, colaboración y código público, visita GitHub. Para sitios web y proyectos comerciales, contacta con SLEEP LATE LAB.","contact.githubCta":"Ver GitHub","contact.commercialCta":"Consultar un proyecto comercial","contact.replyLabel":"Tiempo de respuesta","contact.reply":"Normalmente en 2–3 días laborables","contact.modeLabel":"Colaboración","contact.mode":"Remota","contact.regionLabel":"Regiones","contact.region":"Japón・Taiwán・Todo el mundo",
    "details.projectsTitle":"Detalles de proyectos","details.projectsIntro":"Experiencia de desarrollo que incluye sitios de clientes, WordPress, sitios estáticos, API, proyectos privados y repositorios públicos.","details.publicOnly":"Los repositorios públicos adicionales se cargan mediante la API de GitHub. Las consultas comerciales se gestionan en SLEEP LATE LAB.","details.profileTitle":"Educación, formación internacional y certificaciones","details.profileIntro":"Historial detallado de educación y formación separado de la página principal. No se publican enlaces a certificados.",
    "a11y.skip":"Saltar al contenido","a11y.home":"Inicio del portfolio de Koshi","a11y.openMenu":"Abrir menú","a11y.navigation":"Navegación principal","a11y.logoAlt":"Logotipo de Koshi","a11y.scrollProjects":"Ir a proyectos destacados","a11y.portraitAlt":"Retrato de Koshi Sugawara","a11y.backTop":"Volver arriba"
  }
};

Object.entries(extendedTranslations).forEach(([language, values]) => {
  Object.assign(translations[language], values);
  // No key may silently fall back to another language. Technical proper nouns
  // are intentionally preserved, while UI labels use the localized dictionary.
  Object.keys(translations.en).forEach((key) => {
    if (!(key in translations[language])) translations[language][key] = values[key] || translations.en[key];
  });
});

const translationComplements = {
  "zh-CN":{"a11y.closeMenu":"关闭菜单","certifications.languages":"语言学习","certifications.education":"心理、教育与社会","certifications.technology":"IT与开发","certifications.health":"健康与健身","certifications.creative":"艺术、设计与媒体","certifications.other":"其他资格与学习经历","status.client":"客户项目","status.legacy":"旧网站","status.prototype":"原型","status.learning":"学习项目","status.planned":"计划中","meta.title":"Koshi｜多语言Web开发者作品集","meta.description":"菅原鸿志的多语言Web开发与公开项目技术作品集。","details.projectsMeta":"项目详情｜Koshi开发者作品集","details.profileMeta":"教育与资格｜Koshi开发者作品集"},
  ko:{"a11y.closeMenu":"메뉴 닫기","certifications.languages":"언어 학습","certifications.education":"심리·교육·사회","certifications.technology":"IT·개발","certifications.health":"건강·피트니스","certifications.creative":"예술·디자인·미디어","certifications.other":"기타 자격 및 학습","status.client":"고객 프로젝트","status.legacy":"레거시","status.prototype":"프로토타입","status.learning":"학습 프로젝트","status.planned":"예정","meta.title":"Koshi | 다국어 웹 개발자 포트폴리오","meta.description":"Koshi Sugawara의 다국어 웹 개발 및 공개 프로젝트 기술 포트폴리오입니다.","details.projectsMeta":"프로젝트 상세 | Koshi 개발자 포트폴리오","details.profileMeta":"학력 및 자격 | Koshi 개발자 포트폴리오"},
  th:{"a11y.closeMenu":"ปิดเมนู","certifications.languages":"การเรียนภาษา","certifications.education":"จิตวิทยา การศึกษา และสังคม","certifications.technology":"ไอทีและการพัฒนา","certifications.health":"สุขภาพและฟิตเนส","certifications.creative":"ศิลปะ การออกแบบ และสื่อ","certifications.other":"คุณวุฒิและการเรียนรู้อื่น","status.client":"งานลูกค้า","status.legacy":"เว็บไซต์เดิม","status.prototype":"ต้นแบบ","status.learning":"โปรเจกต์เพื่อการเรียนรู้","status.planned":"วางแผนไว้","meta.title":"Koshi | พอร์ตโฟลิโอนักพัฒนาเว็บหลายภาษา","meta.description":"พอร์ตโฟลิโอด้านการพัฒนาเว็บหลายภาษาและโปรเจกต์สาธารณะของ Koshi Sugawara","details.projectsMeta":"รายละเอียดโปรเจกต์ | พอร์ตโฟลิโอนักพัฒนา Koshi","details.profileMeta":"การศึกษาและคุณวุฒิ | พอร์ตโฟลิโอนักพัฒนา Koshi"},
  vi:{"a11y.closeMenu":"Đóng menu","certifications.languages":"Học ngôn ngữ","certifications.education":"Tâm lý, giáo dục và xã hội","certifications.technology":"CNTT và phát triển","certifications.health":"Sức khỏe và thể chất","certifications.creative":"Nghệ thuật, thiết kế và truyền thông","certifications.other":"Chứng chỉ và học tập khác","status.client":"Dự án khách hàng","status.legacy":"Website cũ","status.prototype":"Nguyên mẫu","status.learning":"Dự án học tập","status.planned":"Dự kiến","meta.title":"Koshi | Portfolio lập trình viên web đa ngôn ngữ","meta.description":"Portfolio kỹ thuật về phát triển web đa ngôn ngữ và các dự án công khai của Koshi Sugawara.","details.projectsMeta":"Chi tiết dự án | Portfolio lập trình viên Koshi","details.profileMeta":"Học vấn và chứng chỉ | Portfolio lập trình viên Koshi"},
  es:{"a11y.closeMenu":"Cerrar menú","certifications.languages":"Aprendizaje de idiomas","certifications.education":"Psicología, educación y sociedad","certifications.technology":"TI y desarrollo","certifications.health":"Salud y actividad física","certifications.creative":"Arte, diseño y medios","certifications.other":"Otras certificaciones y formación","status.client":"Trabajo para cliente","status.legacy":"Sitio anterior","status.prototype":"Prototipo","status.learning":"Proyecto de aprendizaje","status.planned":"Planificado","meta.title":"Koshi | Portfolio de desarrollador web multilingüe","meta.description":"Portfolio técnico de desarrollo web multilingüe y proyectos públicos de Koshi Sugawara.","details.projectsMeta":"Detalles de proyectos | Portfolio de Koshi","details.profileMeta":"Educación y certificaciones | Portfolio de Koshi"}
};
Object.entries(translationComplements).forEach(([language, values]) => Object.assign(translations[language], values));

Object.assign(translations["zh-CN"], {"project.jobs":"用于搜索和浏览职位信息的Svelte前端。","project.ecommerce":"前端与API分离的Svelte全栈电商原型。","project.portfolio":"面向GitHub Pages的多语言响应式开发者作品集。","project.luno":"比较两个交易所比特币价格的命令行工具。","project.corporate":"从企划到上线全程负责的付费企业网站项目。","project.photographer":"使用WordPress与Divi制作的旧版摄影作品集。"});
Object.assign(translations.ko, {"project.jobs":"채용 정보를 검색하고 열람하는 Svelte 프런트엔드.","project.ecommerce":"프런트엔드와 API를 분리한 Svelte 풀스택 커머스 프로토타입.","project.portfolio":"GitHub Pages용 다국어 반응형 개발자 포트폴리오.","project.luno":"두 거래소의 비트코인 가격을 비교하는 명령줄 도구.","project.corporate":"기획부터 공개까지 담당한 유료 기업 웹사이트 프로젝트.","project.photographer":"WordPress와 Divi로 제작한 이전 사진 포트폴리오."});
Object.assign(translations.th, {"project.jobs":"ฟรอนต์เอนด์ Svelte สำหรับค้นหาและดูข้อมูลงาน","project.ecommerce":"ต้นแบบอีคอมเมิร์ซแบบฟูลสแตกด้วย Svelte ที่แยกฟรอนต์เอนด์และ API","project.portfolio":"พอร์ตโฟลิโอนักพัฒนาแบบหลายภาษาและ responsive สำหรับ GitHub Pages","project.luno":"เครื่องมือบรรทัดคำสั่งสำหรับเปรียบเทียบราคาบิตคอยน์จากสองตลาด","project.corporate":"โครงการเว็บไซต์บริษัทแบบมีค่าจ้างที่ดูแลตั้งแต่การวางแผนจนถึงเผยแพร่","project.photographer":"พอร์ตโฟลิโอภาพถ่ายเวอร์ชันเดิมที่สร้างด้วย WordPress และ Divi"});
Object.assign(translations.vi, {"project.jobs":"Giao diện Svelte để tìm kiếm và xem thông tin tuyển dụng.","project.ecommerce":"Nguyên mẫu thương mại điện tử full-stack bằng Svelte với front-end và API tách biệt.","project.portfolio":"Portfolio lập trình viên đa ngôn ngữ, đáp ứng cho GitHub Pages.","project.luno":"Công cụ dòng lệnh so sánh giá Bitcoin giữa hai sàn.","project.corporate":"Dự án website doanh nghiệp có trả phí, phụ trách từ lập kế hoạch đến xuất bản.","project.photographer":"Portfolio nhiếp ảnh cũ được xây dựng bằng WordPress và Divi."});
Object.assign(translations.es, {"project.jobs":"Interfaz Svelte para buscar y consultar oportunidades de empleo.","project.ecommerce":"Prototipo de comercio electrónico full-stack en Svelte con front-end y API separados.","project.portfolio":"Portfolio de desarrollador multilingüe y responsivo para GitHub Pages.","project.luno":"Herramienta de línea de comandos que compara el precio de Bitcoin entre dos mercados.","project.corporate":"Sitio web corporativo remunerado realizado desde la planificación hasta la publicación.","project.photographer":"Portfolio de fotografía anterior creado con WordPress y Divi."});

const projectPageComplements = {
  en:{"section.wordpressArchive":"WordPress & Archive","section.publicProjects":"Public Development Projects","section.commercialProjects":"Commercial Projects","commercial.body":"Web production and commercial project inquiries are handled by SLEEP LATE LAB.","commercial.services":"View services →","commercial.contact":"Discuss a project →","project.value":"Project value","project.codeAvailability":"Code availability","project.codePrivate":"Private / Not publicly available","project.codePublic":"Public GitHub repository","project.vouvray":"A bilingual e-commerce website developed for a French winery.","project.sleepLegacy":"The first SLEEP LATE LAB website, built to communicate its early business activities."},
  ja:{"section.wordpressArchive":"WordPress・旧サイト","section.publicProjects":"Public開発プロジェクト","section.commercialProjects":"商用プロジェクト","commercial.body":"Web制作や商用案件のご相談はSLEEP LATE LABで受け付けています。","commercial.services":"サービスを見る →","commercial.contact":"相談する →","project.value":"案件規模","project.codeAvailability":"コード公開","project.codePrivate":"非公開 / 一般公開なし","project.codePublic":"Public GitHubリポジトリ","project.vouvray":"フランスのワイナリー向けに開発した英語・フランス語対応のECサイト。","project.sleepLegacy":"初期の事業内容を伝えるために制作した、SLEEP LATE LABの最初のWebサイト。"},
  "zh-TW":{"section.wordpressArchive":"WordPress 與舊網站","section.publicProjects":"公開開發專案","section.commercialProjects":"商業專案","commercial.body":"網站製作與商業專案諮詢由 SLEEP LATE LAB 受理。","commercial.services":"查看服務 →","commercial.contact":"洽談專案 →","project.value":"專案金額","project.codeAvailability":"程式碼公開狀態","project.codePrivate":"非公開 / 不提供公開存取","project.codePublic":"公開 GitHub 儲存庫","project.vouvray":"為法國酒莊開發的英法雙語電商網站。","project.sleepLegacy":"為呈現早期業務而製作的 SLEEP LATE LAB 初代網站。"},
  "zh-CN":{"section.wordpressArchive":"WordPress 与旧网站","section.publicProjects":"公开开发项目","section.commercialProjects":"商业项目","commercial.body":"网站制作与商业项目咨询由 SLEEP LATE LAB 受理。","commercial.services":"查看服务 →","commercial.contact":"咨询项目 →","project.value":"项目金额","project.codeAvailability":"代码公开状态","project.codePrivate":"不公开 / 不提供公开访问","project.codePublic":"公开 GitHub 仓库","project.vouvray":"为法国酒庄开发的英法双语电商网站。","project.sleepLegacy":"为展示早期业务而制作的 SLEEP LATE LAB 初代网站。"},
  ko:{"section.wordpressArchive":"WordPress 및 이전 사이트","section.publicProjects":"공개 개발 프로젝트","section.commercialProjects":"상업 프로젝트","commercial.body":"웹 제작 및 상업 프로젝트 상담은 SLEEP LATE LAB에서 접수합니다.","commercial.services":"서비스 보기 →","commercial.contact":"프로젝트 상담 →","project.value":"프로젝트 금액","project.codeAvailability":"코드 공개 여부","project.codePrivate":"비공개 / 공개 접근 불가","project.codePublic":"공개 GitHub 저장소","project.vouvray":"프랑스 와이너리를 위해 개발한 영어·프랑스어 전자상거래 사이트입니다.","project.sleepLegacy":"초기 사업 활동을 소개하기 위해 만든 SLEEP LATE LAB의 첫 웹사이트입니다."},
  th:{"section.wordpressArchive":"WordPress และเว็บไซต์เดิม","section.publicProjects":"โปรเจกต์พัฒนาสาธารณะ","section.commercialProjects":"โปรเจกต์เชิงพาณิชย์","commercial.body":"SLEEP LATE LAB รับคำปรึกษาด้านการสร้างเว็บไซต์และโปรเจกต์เชิงพาณิชย์","commercial.services":"ดูบริการ →","commercial.contact":"ปรึกษาโปรเจกต์ →","project.value":"มูลค่าโปรเจกต์","project.codeAvailability":"สถานะการเปิดเผยโค้ด","project.codePrivate":"ส่วนตัว / ไม่เปิดเผยต่อสาธารณะ","project.codePublic":"รีโพซิทอรี GitHub สาธารณะ","project.vouvray":"เว็บไซต์อีคอมเมิร์ซสองภาษาที่พัฒนาสำหรับโรงบ่มไวน์ในฝรั่งเศส","project.sleepLegacy":"เว็บไซต์แรกของ SLEEP LATE LAB ที่สร้างขึ้นเพื่อนำเสนอกิจกรรมทางธุรกิจในช่วงเริ่มต้น"},
  vi:{"section.wordpressArchive":"WordPress và website cũ","section.publicProjects":"Dự án phát triển công khai","section.commercialProjects":"Dự án thương mại","commercial.body":"SLEEP LATE LAB tiếp nhận yêu cầu tư vấn sản xuất website và dự án thương mại.","commercial.services":"Xem dịch vụ →","commercial.contact":"Trao đổi dự án →","project.value":"Giá trị dự án","project.codeAvailability":"Trạng thái công khai mã","project.codePrivate":"Riêng tư / Không công khai","project.codePublic":"Kho GitHub công khai","project.vouvray":"Website thương mại điện tử song ngữ được phát triển cho một nhà rượu vang Pháp.","project.sleepLegacy":"Website đầu tiên của SLEEP LATE LAB, được xây dựng để giới thiệu hoạt động kinh doanh ban đầu."},
  es:{"section.wordpressArchive":"WordPress y sitios anteriores","section.publicProjects":"Proyectos de desarrollo públicos","section.commercialProjects":"Proyectos comerciales","commercial.body":"SLEEP LATE LAB atiende las consultas sobre sitios web y proyectos comerciales.","commercial.services":"Ver servicios →","commercial.contact":"Consultar un proyecto →","project.value":"Valor del proyecto","project.codeAvailability":"Disponibilidad del código","project.codePrivate":"Privado / No disponible públicamente","project.codePublic":"Repositorio público de GitHub","project.vouvray":"Sitio de comercio electrónico bilingüe desarrollado para una bodega francesa.","project.sleepLegacy":"El primer sitio de SLEEP LATE LAB, creado para presentar sus actividades iniciales."}
};
Object.entries(projectPageComplements).forEach(([language, values]) => Object.assign(translations[language], values));

const githubMetricComplements = {
  en:{"github.stars":"Stars","github.forks":"Forks"}, ja:{"github.stars":"スター","github.forks":"フォーク"},
  "zh-TW":{"github.stars":"星號","github.forks":"分支"}, "zh-CN":{"github.stars":"星标","github.forks":"分支"},
  ko:{"github.stars":"스타","github.forks":"포크"}, th:{"github.stars":"ดาว","github.forks":"ฟอร์ก"},
  vi:{"github.stars":"Sao","github.forks":"Bản phân nhánh"}, es:{"github.stars":"Estrellas","github.forks":"Bifurcaciones"}
};
Object.entries(githubMetricComplements).forEach(([language, values]) => Object.assign(translations[language], values));

const detailLinkComplements = {
  en:{"project.details":"View details"},ja:{"project.details":"詳細を見る"},"zh-TW":{"project.details":"查看詳情"},"zh-CN":{"project.details":"查看详情"},
  ko:{"project.details":"상세 보기"},th:{"project.details":"ดูรายละเอียด"},vi:{"project.details":"Xem chi tiết"},es:{"project.details":"Ver detalles"}
};
Object.entries(detailLinkComplements).forEach(([language, values]) => Object.assign(translations[language], values));

const heroCommercialTranslations = {
  en:"Commercial Services", ja:"商用サービス", "zh-TW":"商業服務", "zh-CN":"商业服务",
  ko:"상업 서비스", th:"บริการเชิงพาณิชย์", vi:"Dịch vụ thương mại", es:"Servicios comerciales"
};
Object.entries(heroCommercialTranslations).forEach(([language, value]) => { translations[language]["hero.commercial"] = value; });

const careerSummaryTranslations = {
  en:"Awaiting final degree-completion results from Hokkaido Information University. Admitted to Wenzao’s Master’s Program in International Business Administration, with enrollment expected in September 2026.",
  ja:"北海道情報大学の卒業要件に関する最終結果待ち。文藻外語大学 国際企業管理系修士課程に合格し、2026年9月入学予定。",
  "zh-TW":"目前等待北海道情報大學學位完成的最終結果。已錄取文藻外語大學國際企業管理系碩士班，預計2026年9月入學。",
  "zh-CN":"目前等待北海道情报大学学位完成的最终结果。已录取文藻外语大学国际企业管理硕士课程，预计2026年9月入学。",
  ko:"홋카이도정보대학교 학위 완료 최종 결과를 기다리고 있습니다. 원자오외국어대학교 국제기업관리 석사과정에 합격했으며 2026년 9월 입학 예정입니다.",
  th:"กำลังรอผลสุดท้ายเกี่ยวกับการสำเร็จการศึกษาจากมหาวิทยาลัยสารสนเทศฮอกไกโด และได้รับการตอบรับเข้าหลักสูตรปริญญาโทบริหารธุรกิจระหว่างประเทศของมหาวิทยาลัยภาษาเหวินจ่าว โดยคาดว่าจะเข้าเรียนในเดือนกันยายน 2026",
  vi:"Đang chờ kết quả cuối cùng về việc hoàn tất bằng cấp tại Đại học Thông tin Hokkaido. Đã trúng tuyển chương trình Thạc sĩ Quản trị Kinh doanh Quốc tế tại Wenzao, dự kiến nhập học tháng 9/2026.",
  es:"A la espera del resultado final de finalización del grado en Hokkaido Information University. Admitido en el máster de Administración de Empresas Internacionales de Wenzao, con ingreso previsto en septiembre de 2026."
};
Object.entries(careerSummaryTranslations).forEach(([language, value]) => { translations[language]["career.2026summary"] = value; });

const developerCredentialTranslations = {
  en:{"credentials.developerTitle":"Developer-related credentials","credentials.developerIntro":"Only credentials and completed courses related to web, IT, design, digital marketing, and AI are listed. Evidence links are not published.","credentials.fullProfile":"View education, languages, and other experience on the personal profile ↗"},
  ja:{"credentials.developerTitle":"開発・デジタル関連の資格","credentials.developerIntro":"Web、IT、デザイン、デジタルマーケティング、AIに関連する資格・修了講座のみ掲載しています。証明書リンクは公開していません。","credentials.fullProfile":"学歴・語学・その他の経歴は個人プロフィールで見る ↗"},
  "zh-TW":{"credentials.developerTitle":"開發與數位相關資格","credentials.developerIntro":"僅列出與網頁、IT、設計、數位行銷及AI相關的資格與結業課程，不公開證明文件連結。","credentials.fullProfile":"前往個人網站查看學歷、語言與其他經歷 ↗"},
  "zh-CN":{"credentials.developerTitle":"开发与数字相关资格","credentials.developerIntro":"仅列出与网页、IT、设计、数字营销及AI相关的资格与结业课程，不公开证明文件链接。","credentials.fullProfile":"前往个人网站查看学历、语言与其他经历 ↗"},
  ko:{"credentials.developerTitle":"개발·디지털 관련 자격","credentials.developerIntro":"웹, IT, 디자인, 디지털 마케팅 및 AI 관련 자격과 수료 과정만 게재하며 증빙 링크는 공개하지 않습니다.","credentials.fullProfile":"학력, 언어 및 기타 경력은 개인 프로필에서 보기 ↗"},
  th:{"credentials.developerTitle":"คุณวุฒิด้านการพัฒนาและดิจิทัล","credentials.developerIntro":"แสดงเฉพาะคุณวุฒิและหลักสูตรที่เกี่ยวข้องกับเว็บ ไอที การออกแบบ การตลาดดิจิทัล และ AI โดยไม่เผยแพร่ลิงก์เอกสารรับรอง","credentials.fullProfile":"ดูการศึกษา ภาษา และประสบการณ์อื่นในเว็บไซต์ส่วนตัว ↗"},
  vi:{"credentials.developerTitle":"Chứng chỉ phát triển và kỹ thuật số","credentials.developerIntro":"Chỉ hiển thị chứng chỉ và khóa học liên quan đến web, CNTT, thiết kế, tiếp thị số và AI; không công khai liên kết minh chứng.","credentials.fullProfile":"Xem học vấn, ngôn ngữ và kinh nghiệm khác trên hồ sơ cá nhân ↗"},
  es:{"credentials.developerTitle":"Credenciales de desarrollo y ámbito digital","credentials.developerIntro":"Solo se muestran credenciales y cursos de web, TI, diseño, marketing digital e IA. No se publican enlaces a documentos acreditativos.","credentials.fullProfile":"Ver formación, idiomas y otra experiencia en el perfil personal ↗"}
};
Object.entries(developerCredentialTranslations).forEach(([language, values]) => Object.assign(translations[language], values));
