// UI translations. Project and technology names remain in their official form.
const translations = {
  en: {
    "nav.home":"Home","nav.about":"About","nav.skills":"Skills","nav.certifications":"Qualifications","nav.featured":"Featured Projects","nav.otherProjects":"Other Projects","nav.experiments":"Experiments","nav.github":"GitHub","nav.contact":"Contact","language.label":"Language",
    "hero.eyebrow":"Developer / Engineer","hero.title":"Building practical web products across languages and borders.","hero.copy":"I plan, design, and develop simple web products for multilingual communities in Japan, Taiwan, and across Asia.","hero.projects":"View projects",
    "section.about":"About","section.skills":"Skills","section.certifications":"Qualifications & Learning","section.featured":"Featured Projects","section.otherProjects":"Other Projects","section.experiments":"Experiments","section.contact":"Contact",
    "about.lead":"I am a developer working mainly between Japan and Taiwan, focused on multilingual web development and independent products.","about.body":"After studying in several countries, I now plan, design, build, and publish projects independently. I combine WordPress, front-end and back-end development, APIs, SEO, and responsive design with experience in languages, travel, education, photography, video, and copywriting.","about.focusLabel":"Focus","about.focus":"Web development, WordPress, independent products","about.locationLabel":"Location","about.location":"Japan / Taiwan · Remote","about.languagesLabel":"Languages","about.languages":"Japanese, English, Mandarin, Thai",
    "projects.intro":"Public repositories are loaded automatically from GitHub.",
    "skills.usedIn":"Used in","certifications.intro":"Qualifications, certifications, awards, and completed courses. Evidence links are not published.","certifications.languages":"Language Learning","certifications.education":"Psychology, Education & Society","certifications.technology":"IT & Development","certifications.health":"Health & Fitness","certifications.creative":"Art, Design & Media","certifications.other":"Other Qualifications & Learning",
    "project.jobs":"A full-stack job platform with separate Svelte frontend and containerized backend repositories.","project.ecommerce":"An e-commerce application built as separate frontend and backend services.","project.luno":"Compares real-time Bitcoin prices between Binance and Luno and calculates the market premium.","project.email":"Monitors an inbox and sends automated responses with Node.js, Nodemailer, and IMAP.","project.portfolio":"This multilingual, responsive developer portfolio, built for GitHub Pages without a framework.",
    "experiments.intro":"Small prototypes used to explore interfaces, data structures, and multilingual ideas.","skills.primary":"Primary","skills.working":"Working Knowledge","skills.creative":"Creative","project.technologies":"Technologies","project.github":"GitHub","project.demo":"Demo","project.noDescription":"Description is being prepared.","project.notSpecified":"Not specified","project.updated":"Updated","projects.loading":"Loading public repositories from GitHub…","projects.empty":"No public repositories are available.","projects.error":"Public repositories could not be loaded. Please visit the GitHub profile.","status.public":"Public","status.archived":"Archived","language.full":"Full translations","language.partial":"Partial translations","a11y.skip":"Skip to content","a11y.home":"Koshi portfolio home","a11y.openMenu":"Open menu","a11y.closeMenu":"Close menu","a11y.navigation":"Main navigation","a11y.logoAlt":"Koshi logo","a11y.scrollAbout":"Scroll to About","a11y.portraitAlt":"Portrait of Koshi Sugawara","a11y.backTop":"Back to top","meta.title":"Koshi | Multilingual Web Developer Portfolio","meta.description":"Developer portfolio of Koshi Sugawara, building multilingual web products for Japan, Taiwan, and communities across Asia.",
    "github.lead":"Source code, experiments, and ongoing development are available on GitHub.","github.body":"Browse my public repositories to see implementation details, project structure, and development history.","github.cta":"View GitHub profile","contact.lead":"Have a project or collaboration in mind?","contact.body":"Feel free to get in touch by email or connect with me online."
  },
  ja: {
    "nav.home":"ホーム","nav.about":"プロフィール","nav.skills":"スキル","nav.certifications":"資格・学習歴","nav.featured":"注目プロジェクト","nav.otherProjects":"その他のプロジェクト","nav.experiments":"実験・試作","nav.github":"GitHub","nav.contact":"お問い合わせ","language.label":"言語",
    "hero.eyebrow":"開発者 / エンジニア","hero.title":"言語と国境を越えて、実用的なWebプロダクトをつくる。","hero.copy":"日本・台湾・アジアの多言語コミュニティに向け、シンプルなWebプロダクトを企画・設計・開発しています。","hero.projects":"プロジェクトを見る",
    "section.about":"プロフィール","section.skills":"スキル","section.certifications":"資格・認定・学習歴","section.featured":"注目プロジェクト","section.otherProjects":"その他のプロジェクト","section.experiments":"実験・試作","section.contact":"お問い合わせ",
    "about.lead":"日本と台湾を中心に、多言語Web開発と個人開発に取り組む開発者です。","about.body":"複数の国で学んだ経験を活かし、企画、設計、実装、公開まで個人で行っています。WordPress、フロントエンド・バックエンド、API、SEO、レスポンシブデザインに、語学、旅行、教育、写真、映像、コピーライティングの知識を組み合わせます。","about.focusLabel":"専門","about.focus":"Web開発、WordPress、個人開発","about.locationLabel":"拠点","about.location":"日本 / 台湾・リモート","about.languagesLabel":"言語","about.languages":"日本語、英語、中国語、タイ語",
    "projects.intro":"GitHubのPublicリポジトリを自動で読み込んで表示します。",
    "skills.usedIn":"使用プロジェクト","certifications.intro":"資格、認定、受賞歴、修了した講座を掲載しています。証明書リンクは公開していません。","certifications.languages":"語学","certifications.education":"心理・教育・社会","certifications.technology":"IT・開発","certifications.health":"健康・フィットネス","certifications.creative":"アート・デザイン・メディア","certifications.other":"その他の資格・学習歴",
    "project.jobs":"Svelteのフロントエンドとコンテナ化したバックエンドで構成するフルスタック求人プラットフォーム。","project.ecommerce":"フロントエンドとバックエンドを分離して構築したECアプリケーション。","project.luno":"BinanceとLunoのBitcoin価格をリアルタイムで比較し、市場プレミアムを計算します。","project.email":"Node.js、Nodemailer、IMAPで受信箱を監視し、自動返信を行うツール。","project.portfolio":"フレームワークを使わずGitHub Pages向けに構築した、多言語・レスポンシブ対応の開発者ポートフォリオ。",
    "experiments.intro":"インターフェース、データ構造、多言語アイデアを検証する小規模な試作です。","skills.primary":"Primary / 主力スキル","skills.working":"Working Knowledge / 実務・開発経験","skills.creative":"Creative / 制作スキル","project.technologies":"使用技術","project.github":"GitHub","project.demo":"デモ","project.noDescription":"説明を準備中です。","project.notSpecified":"未指定","project.updated":"更新","projects.loading":"GitHubからPublicリポジトリを読み込んでいます…","projects.empty":"表示できるPublicリポジトリはありません。","projects.error":"Publicリポジトリを読み込めませんでした。GitHubプロフィールをご覧ください。","status.public":"公開","status.archived":"アーカイブ済み","language.full":"完全対応","language.partial":"一部翻訳","a11y.skip":"本文へ移動","a11y.home":"Koshiポートフォリオのホーム","a11y.openMenu":"メニューを開く","a11y.closeMenu":"メニューを閉じる","a11y.navigation":"メインナビゲーション","a11y.logoAlt":"Koshiのロゴ","a11y.scrollAbout":"プロフィールへ移動","a11y.portraitAlt":"菅原鴻志のプロフィール写真","a11y.backTop":"ページ上部へ戻る","meta.title":"Koshi | 多言語Web開発者ポートフォリオ","meta.description":"日本・台湾・アジアの多言語コミュニティに向けてWebプロダクトを開発する、菅原鴻志の技術ポートフォリオ。",
    "github.lead":"ソースコード、実験、継続中の開発をGitHubで管理しています。","github.body":"公開リポジトリでは、実装内容、プロジェクト構成、開発履歴を確認できます。","github.cta":"GitHubプロフィールを見る","contact.lead":"プロジェクトや協業のご相談がありますか？","contact.body":"メールまたはオンラインプロフィールからお気軽にご連絡ください。"
  },
  "zh-TW": {
    "nav.home":"首頁","nav.about":"關於我","nav.skills":"技能","nav.certifications":"資格與學習","nav.featured":"精選專案","nav.otherProjects":"其他專案","nav.experiments":"實驗原型","nav.github":"GitHub","nav.contact":"聯絡","language.label":"語言",
    "hero.eyebrow":"開發者 / 工程師","hero.title":"跨越語言與國界，打造實用的網路產品。","hero.copy":"為日本、台灣與亞洲的多語言社群，企劃、設計並開發簡單易用的網路產品。","hero.projects":"查看專案","section.about":"關於我","section.skills":"技能","section.certifications":"資格、認證與學習經歷","section.featured":"精選專案","section.otherProjects":"其他專案","section.experiments":"實驗原型","section.contact":"聯絡",
    "about.lead":"主要在日本與台灣活動，專注於多語言網頁開發與獨立產品。","about.body":"結合在多個國家學習的經驗，獨立完成企劃、設計、實作與發布。將WordPress、前後端開發、API、SEO與響應式設計，結合語言、旅行、教育、攝影、影片與文案知識。","about.focusLabel":"專長","about.focus":"網頁開發、WordPress、獨立產品","about.locationLabel":"地點","about.location":"日本 / 台灣・遠端","about.languagesLabel":"語言","about.languages":"日語、英語、華語、泰語",
    "skills.usedIn":"使用專案","certifications.intro":"整理資格、認證、獲獎與已完成課程；不公開證明文件連結。","certifications.languages":"語言學習","certifications.education":"心理、教育與社會","certifications.technology":"IT與開發","certifications.health":"健康與體適能","certifications.creative":"藝術、設計與媒體","certifications.other":"其他資格與學習經歷",
    "projects.intro":"自動從GitHub載入並顯示Public儲存庫。","project.jobs":"由 Svelte 前端與容器化後端組成的全端求職平台。","project.ecommerce":"以前後端分離方式建立的電子商務應用程式。","project.luno":"即時比較 Binance 與 Luno 的比特幣價格並計算溢價。","project.email":"使用 Node.js、Nodemailer 與 IMAP 監控信箱並自動回覆。","project.portfolio":"不使用框架、為 GitHub Pages 建立的多語言響應式作品集。",
    "experiments.intro":"用來探索介面、資料結構與多語言想法的小型原型。","skills.primary":"主要技能","skills.working":"實作經驗","skills.creative":"創意製作","project.technologies":"使用技術","project.github":"GitHub","project.demo":"展示","project.noDescription":"說明準備中。","project.notSpecified":"未指定","project.updated":"更新","projects.loading":"正在從GitHub載入Public儲存庫…","projects.empty":"目前沒有可顯示的Public儲存庫。","projects.error":"無法載入Public儲存庫，請前往GitHub個人頁面查看。","status.public":"公開","status.archived":"已封存","language.full":"完整翻譯","language.partial":"部分翻譯","a11y.skip":"跳至主要內容","a11y.home":"Koshi作品集首頁","a11y.openMenu":"開啟選單","a11y.closeMenu":"關閉選單","a11y.navigation":"主要導覽","a11y.logoAlt":"Koshi標誌","a11y.scrollAbout":"前往關於我","a11y.portraitAlt":"菅原鴻志的個人照片","a11y.backTop":"返回頁首","meta.title":"Koshi | 多語言網頁開發者作品集","meta.description":"菅原鴻志的技術作品集，為日本、台灣與亞洲多語言社群開發實用的網路產品。",
    "github.lead":"程式碼、實驗與持續開發內容都在GitHub管理。","github.body":"可在公開儲存庫查看實作細節、專案結構與開發紀錄。","github.cta":"查看 GitHub 個人頁面","contact.lead":"有專案或合作想法嗎？","contact.body":"歡迎透過電子郵件或線上平台與我聯絡。"
  },
  "zh-CN": {"nav.home":"首页","nav.about":"关于我","nav.skills":"技能","nav.featured":"精选项目","nav.otherProjects":"其他项目","nav.github":"GitHub","nav.contact":"联系","language.label":"语言","hero.eyebrow":"开发者 / 工程师","hero.title":"打造实用的网络体验。","hero.copy":"从界面到部署，设计并开发无障碍网站与实用的网络应用。","hero.projects":"查看项目","section.about":"关于我","section.skills":"技能","section.featured":"精选项目","section.otherProjects":"其他项目","section.contact":"联系"},
  ko: {"nav.home":"홈","nav.about":"소개","nav.skills":"기술","nav.featured":"주요 프로젝트","nav.otherProjects":"기타 프로젝트","nav.github":"GitHub","nav.contact":"연락처","language.label":"언어","hero.eyebrow":"개발자 / 엔지니어","hero.title":"웹을 위한 유용한 경험을 만듭니다.","hero.copy":"인터페이스부터 배포까지 접근성 높은 웹사이트와 실용적인 웹 앱을 개발합니다.","hero.projects":"프로젝트 보기","section.about":"소개","section.skills":"기술","section.featured":"주요 프로젝트","section.otherProjects":"기타 프로젝트","section.contact":"연락처"},
  th: {"nav.home":"หน้าแรก","nav.about":"เกี่ยวกับ","nav.skills":"ทักษะ","nav.featured":"โปรเจกต์เด่น","nav.otherProjects":"โปรเจกต์อื่น","nav.github":"GitHub","nav.contact":"ติดต่อ","language.label":"ภาษา","hero.eyebrow":"นักพัฒนา / วิศวกร","hero.title":"สร้างประสบการณ์เว็บที่เป็นประโยชน์","hero.copy":"ออกแบบและพัฒนาเว็บไซต์ที่เข้าถึงได้และเว็บแอปที่ใช้งานจริง ตั้งแต่อินเทอร์เฟซจนถึงการเผยแพร่","hero.projects":"ดูโปรเจกต์","section.about":"เกี่ยวกับ","section.skills":"ทักษะ","section.featured":"โปรเจกต์เด่น","section.otherProjects":"โปรเจกต์อื่น","section.contact":"ติดต่อ"},
  vi: {"nav.home":"Trang chủ","nav.about":"Giới thiệu","nav.skills":"Kỹ năng","nav.featured":"Dự án nổi bật","nav.otherProjects":"Dự án khác","nav.github":"GitHub","nav.contact":"Liên hệ","language.label":"Ngôn ngữ","hero.eyebrow":"Lập trình viên / Kỹ sư","hero.title":"Xây dựng trải nghiệm web hữu ích.","hero.copy":"Thiết kế và phát triển website dễ tiếp cận và ứng dụng web thực tế, từ giao diện đến triển khai.","hero.projects":"Xem dự án","section.about":"Giới thiệu","section.skills":"Kỹ năng","section.featured":"Dự án nổi bật","section.otherProjects":"Dự án khác","section.contact":"Liên hệ"},
  es: {"nav.home":"Inicio","nav.about":"Acerca de","nav.skills":"Habilidades","nav.featured":"Proyectos destacados","nav.otherProjects":"Otros proyectos","nav.github":"GitHub","nav.contact":"Contacto","language.label":"Idioma","hero.eyebrow":"Desarrollador / Ingeniero","hero.title":"Creando experiencias útiles para la web.","hero.copy":"Diseño y desarrollo sitios accesibles y aplicaciones web prácticas, desde la interfaz hasta el despliegue.","hero.projects":"Ver proyectos","section.about":"Acerca de","section.skills":"Habilidades","section.featured":"Proyectos destacados","section.otherProjects":"Otros proyectos","section.contact":"Contacto"}
};

let currentLanguage = "ja";
function getTranslation(key) { return translations[currentLanguage]?.[key] || translations.en[key] || key; }
function getCurrentLanguage() { return currentLanguage; }

function changeLanguage(language) {
  currentLanguage = translations[language] ? language : "en";
  document.documentElement.lang = currentLanguage;
  localStorage.setItem("preferredLanguage", currentLanguage);
  document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = getTranslation(element.dataset.i18n); });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => { element.setAttribute("aria-label", getTranslation(element.dataset.i18nAriaLabel)); });
  document.querySelectorAll("[data-i18n-alt]").forEach((element) => { element.alt = getTranslation(element.dataset.i18nAlt); });
  document.querySelectorAll("[data-i18n-label]").forEach((element) => { element.label = getTranslation(element.dataset.i18nLabel); });
  document.title = getTranslation("meta.title");
  const description = document.querySelector('meta[name="description"]');
  if (description) description.content = getTranslation("meta.description");
  document.querySelectorAll('meta[property="og:title"], meta[name="twitter:title"]').forEach((element) => { element.content = getTranslation("meta.title"); });
  document.querySelectorAll('meta[property="og:description"], meta[name="twitter:description"]').forEach((element) => { element.content = getTranslation("meta.description"); });
  const selector = document.getElementById("language-select");
  if (selector) selector.value = currentLanguage;
  document.dispatchEvent(new CustomEvent("languagechange", { detail: currentLanguage }));
}

window.getTranslation = getTranslation;
window.getCurrentLanguage = getCurrentLanguage;
window.changeLanguage = changeLanguage;

document.addEventListener("DOMContentLoaded", () => {
  const saved = localStorage.getItem("preferredLanguage");
  const initial = saved && translations[saved] ? saved : "ja";
  changeLanguage(initial);
  document.getElementById("language-select")?.addEventListener("change", (event) => changeLanguage(event.target.value));
});
