// UI translations. Project and technology names remain in their official form.
const translations = {
  en: {
    "nav.home":"Home","nav.about":"About","nav.career":"Education & Career","nav.skills":"Skills","nav.certifications":"Qualifications","nav.featured":"Featured Projects","nav.otherProjects":"Other Projects","nav.experiments":"Experiments","nav.github":"GitHub","nav.contact":"Contact","language.label":"Language",
    "hero.eyebrow":"Developer / Engineer","hero.title":"Building practical web products across languages and borders.","hero.copy":"I plan, design, and develop simple web products for multilingual communities in Japan, Taiwan, and across Asia.","hero.projects":"View projects",
    "section.about":"About","section.career":"Education & Career","section.skills":"Skills","section.certifications":"Qualifications & Learning","section.featured":"Featured Projects","section.otherProjects":"Other Projects","section.experiments":"Experiments","section.contact":"Contact",
    "about.lead":"I am a developer working mainly between Japan and Taiwan, focused on multilingual web development and independent products.","about.body":"After studying in several countries, I now plan, design, build, and publish projects independently. I combine WordPress, front-end and back-end development, APIs, SEO, and responsive design with experience in languages, travel, education, photography, video, and copywriting.","about.focusLabel":"Focus","about.focus":"Web development, WordPress, independent products","about.locationLabel":"Location","about.location":"Japan / Taiwan · Remote","about.languagesLabel":"Languages","about.languages":"Japanese, English, Mandarin, Thai",
    "career.1997":"Born in Hokkaido, Japan","career.2013a":"Completed the University of the Visayas ESL Program","career.2013b":"Graduated from Asuka Mirai High School","career.2017":"Studied Communication at Emporia State University","career.2018":"Completed the Mandarin program at Chinese Culture University","career.2019":"Studied Computer Science at National Taiwan Normal University","career.2020a":"Completed a leather course at Chiang Mai Polytechnic College","career.2020b":"Completed Chiang Mai University’s Thai Language and Culture Program","career.2020c":"Completed Web Professional and Photography courses at Web Courses Bangkok","career.2021":"Founded Sleep Late Lab","career.2022a":"Started selling Sleep Late Lab leather products","career.2022b":"Completed Korean Level A2 at Seoul Korean Language Academy","career.2023a":"Completed NEXT Academy Full-Stack Web Development","career.2023b":"Completed Gold Sounds Academy DJ Course","career.2024":"Graduated from Otemae University with a Bachelor of Arts, majoring in Psychology","career.2026a":"Expected to graduate from Hokkaido Information University","career.2026b":"Completed four terms of Mandarin study at Wenzao Ursuline University of Languages’ Chinese Language Center, reaching its highest level","career.2026c":"Expected to enter the Master’s Program in International Business Administration at Wenzao Ursuline University of Languages",
    "projects.intro":"Representative projects selected for practical value, completeness, and technical character.",
    "nav.career":"Experience","section.career":"Education & Experience","career.education":"Education","career.professional":"Professional & Projects","career.international":"International Learning","career.2026a":"Currently studying at Hokkaido Information University toward graduation","project.purpose":"Purpose","project.role":"Role","project.tech":"Tech","status.caseStudy":"Case Study","status.active":"Active","skills.experience":"Experience","skills.evidence":"Evidence","certifications.viewAll":"View all credentials","a11y.scrollProjects":"Scroll to projects","section.beyond":"Beyond Code","beyond.body":"Photography, video, writing, and independent brand work inform how I design web experiences.","contact.available":"Available for","contact.web":"Web development","contact.static":"Static site projects","contact.wordpress":"WordPress migration","contact.multilingual":"Multilingual content","contact.collaboration":"Technical collaboration",
    "skills.usedIn":"Used in","certifications.intro":"Qualifications, certifications, awards, and completed courses. Evidence links are not published.","certifications.languages":"Language Learning","certifications.education":"Psychology, Education & Society","certifications.technology":"IT & Development","certifications.health":"Health & Fitness","certifications.creative":"Art, Design & Media","certifications.other":"Other Qualifications & Learning",
    "project.jobs":"A full-stack job platform with separate Svelte frontend and containerized backend repositories.","project.ecommerce":"An e-commerce application built as separate frontend and backend services.","project.luno":"Compares real-time Bitcoin prices between Binance and Luno and calculates the market premium.","project.email":"Monitors an inbox and sends automated responses with Node.js, Nodemailer, and IMAP.","project.portfolio":"This multilingual, responsive developer portfolio, built for GitHub Pages without a framework.",
    "experiments.intro":"Small prototypes used to explore interfaces, data structures, and multilingual ideas.","skills.primary":"Primary","skills.working":"Working Knowledge","skills.creative":"Creative","project.technologies":"Technologies","project.github":"GitHub","project.demo":"Demo","project.noDescription":"Description is being prepared.","project.notSpecified":"Not specified","project.updated":"Updated","projects.loading":"Loading public repositories from GitHub…","projects.empty":"No public repositories are available.","projects.error":"Public repositories could not be loaded. Please visit the GitHub profile.","status.public":"Public","status.archived":"Archived","language.full":"Full translations","language.partial":"Partial translations","a11y.skip":"Skip to content","a11y.home":"Koshi portfolio home","a11y.openMenu":"Open menu","a11y.closeMenu":"Close menu","a11y.navigation":"Main navigation","a11y.logoAlt":"Koshi logo","a11y.scrollAbout":"Scroll to About","a11y.portraitAlt":"Portrait of Koshi Sugawara","a11y.backTop":"Back to top","meta.title":"Koshi | Multilingual Web Developer Portfolio","meta.description":"Developer portfolio of Koshi Sugawara, building multilingual web products for Japan, Taiwan, and communities across Asia.",
    "project.noDescription":"View the public repository for code and implementation details.","project.result":"Result","project.currentState":"Status","project.repositories":"Repositories","projects.apiFallback":"GitHub could not be reached. Showing a locally stored list of public projects.","status.prototype":"Prototype","status.learning":"Learning project","status.planned":"Planned","content.article":"Technical article","content.caseStudy":"Case Study","content.relatedProject":"Related project →","nav.insights":"Articles / Case Studies","section.insights":"Technical Articles & Case Studies","career.clientWeb":"Planned and delivered anonymous corporate websites, including WordPress development, responsive implementation, and SEO (client names withheld under confidentiality).","career.clientLabel":"Client Work","career.clientWebPrice":"Corporate website planning, WordPress development, and SEO (project scale: ¥300,000 plus tax)","career.viewAll":"View all education, international learning, and credentials →","certifications.selected":"Selected Credentials","skills.alsoWorking":"Also working with:","skills.creativeBackground":"Creative background:","about.creative":"Photography, video, and copywriting experience informs my web information architecture and visual communication.","about.personalWork":"Personal work → koshijpn.com","details.projectsTitle":"Project Details","details.projectsIntro":"Purpose, role, outcome, current status, technology, and public repositories for representative projects.","details.publicOnly":"Only Public repositories are loaded from the GitHub API.","details.profileTitle":"Education, International Learning & Credentials","details.profileIntro":"Detailed education and learning records moved from the home page. Evidence links are not published.","details.projectsMeta":"Projects | Koshi Developer Portfolio","details.profileMeta":"Education & Credentials | Koshi Developer Portfolio","github.lead":"Source code, experiments, and ongoing development are available on GitHub.","github.body":"Browse my public repositories to see implementation details, project structure, and development history.","github.cta":"View GitHub profile","contact.lead":"Let’s build something useful together.","contact.body":"For technical discussion, collaboration, and public code, visit GitHub. For web production and commercial projects, contact SLEEP LATE LAB.","contact.githubCta":"View GitHub","contact.commercialCta":"Discuss a commercial project"
  },
  ja: {
    "nav.home":"ホーム","nav.about":"プロフィール","nav.career":"学歴・職歴","nav.skills":"スキル","nav.certifications":"資格・学習歴","nav.featured":"プロジェクト","nav.otherProjects":"その他のプロジェクト","nav.experiments":"実験・試作","nav.github":"GitHub","nav.contact":"お問い合わせ","language.label":"言語",
    "hero.eyebrow":"開発者 / エンジニア","hero.title":"言語と国境を越えて、実用的なWebプロダクトをつくる。","hero.copy":"日本・台湾・アジアの多言語コミュニティに向け、シンプルなWebプロダクトを企画・設計・開発しています。","hero.projects":"プロジェクトを見る",
    "section.about":"プロフィール","section.career":"学歴・職歴","section.skills":"スキル","section.certifications":"資格・認定・学習歴","section.featured":"注目プロジェクト","section.otherProjects":"その他のプロジェクト","section.experiments":"実験・試作","section.contact":"お問い合わせ",
    "about.lead":"日本と台湾を中心に、多言語Web開発と個人開発に取り組む開発者です。","about.body":"複数の国で学んだ経験を活かし、企画、設計、実装、公開まで個人で行っています。WordPress、フロントエンド・バックエンド、API、SEO、レスポンシブデザインに、語学、旅行、教育、写真、映像、コピーライティングの知識を組み合わせます。","about.focusLabel":"専門","about.focus":"Web開発、WordPress、個人開発","about.locationLabel":"拠点","about.location":"日本 / 台湾・リモート","about.languagesLabel":"言語","about.languages":"日本語、英語、中国語、タイ語",
    "career.1997":"北海道生まれ","career.2013a":"University of the Visayas ESLプログラム修了","career.2013b":"飛鳥未来高等学校 卒業","career.2017":"Emporia State University コミュニケーション専攻で学ぶ","career.2018":"中国文化大学 華語中心 修了","career.2019":"国立台湾師範大学 コンピューターサイエンス専攻で学ぶ","career.2020a":"チェンマイ職業訓練校 レザーコース修了","career.2020b":"チェンマイ大学 タイ語・文化プログラム修了","career.2020c":"Web Courses Bangkok Web Professional・Photographyコース修了","career.2021":"Sleep Late Lab設立","career.2022a":"Sleep Late Labで革製品販売を開始","career.2022b":"Seoul Korean Language Academy Level A2修了","career.2023a":"NEXT Academy Full-Stack Web Development修了","career.2023b":"Gold Sounds Academy DJ Course修了","career.2024":"大手前大学 卒業・学士（学術）／心理学メジャー","career.2026a":"北海道情報大学 卒業予定","career.2026b":"文藻外語大学 華語中心の中国語コースを4期にわたり受講し、校内最高レベルを修了","career.2026c":"文藻外語大学 国際企業管理系修士課程 入学予定",
    "projects.intro":"実用性、完成度、技術的な特徴を基準に選んだ代表的なプロジェクトです。",
    "nav.career":"経験","section.career":"学歴・実務・学習経験","career.education":"学歴","career.professional":"実務・プロジェクト","career.international":"国際的な学習経験を見る","career.2026a":"北海道情報大学 在学中・卒業に向けて履修中","project.purpose":"目的","project.role":"担当","project.tech":"使用技術","status.caseStudy":"ケーススタディ","status.active":"運用中","skills.experience":"経験","skills.evidence":"根拠","certifications.viewAll":"全資格・学習歴を見る","a11y.scrollProjects":"注目プロジェクトへ移動","section.beyond":"Beyond Code","beyond.body":"写真、映像、文章、個人ブランド運営の経験をWebの情報設計と表現に活かしています。","contact.available":"対応可能な内容","contact.web":"Web開発","contact.static":"静的サイト制作","contact.wordpress":"WordPress移行","contact.multilingual":"多言語コンテンツ","contact.collaboration":"技術協業",
    "skills.usedIn":"使用プロジェクト","certifications.intro":"資格、認定、受賞歴、修了した講座を掲載しています。証明書リンクは公開していません。","certifications.languages":"語学","certifications.education":"心理・教育・社会","certifications.technology":"IT・開発","certifications.health":"健康・フィットネス","certifications.creative":"アート・デザイン・メディア","certifications.other":"その他の資格・学習歴",
    "project.jobs":"Svelteのフロントエンドとコンテナ化したバックエンドで構成するフルスタック求人プラットフォーム。","project.ecommerce":"フロントエンドとバックエンドを分離して構築したECアプリケーション。","project.luno":"BinanceとLunoのBitcoin価格をリアルタイムで比較し、市場プレミアムを計算します。","project.email":"Node.js、Nodemailer、IMAPで受信箱を監視し、自動返信を行うツール。","project.portfolio":"フレームワークを使わずGitHub Pages向けに構築した、多言語・レスポンシブ対応の開発者ポートフォリオ。",
    "experiments.intro":"インターフェース、データ構造、多言語アイデアを検証する小規模な試作です。","skills.primary":"Primary / 主力スキル","skills.working":"Working Knowledge / 実務・開発経験","skills.creative":"Creative / 制作スキル","project.technologies":"使用技術","project.github":"GitHub","project.demo":"デモ","project.noDescription":"説明を準備中です。","project.notSpecified":"未指定","project.updated":"更新","projects.loading":"GitHubからPublicリポジトリを読み込んでいます…","projects.empty":"表示できるPublicリポジトリはありません。","projects.error":"Publicリポジトリを読み込めませんでした。GitHubプロフィールをご覧ください。","status.public":"公開","status.archived":"アーカイブ済み","language.full":"完全対応","language.partial":"一部翻訳","a11y.skip":"本文へ移動","a11y.home":"Koshiポートフォリオのホーム","a11y.openMenu":"メニューを開く","a11y.closeMenu":"メニューを閉じる","a11y.navigation":"メインナビゲーション","a11y.logoAlt":"Koshiのロゴ","a11y.scrollAbout":"プロフィールへ移動","a11y.portraitAlt":"菅原鴻志のプロフィール写真","a11y.backTop":"ページ上部へ戻る","meta.title":"Koshi | 多言語Web開発者ポートフォリオ","meta.description":"日本・台湾・アジアの多言語コミュニティに向けてWebプロダクトを開発する、菅原鴻志の技術ポートフォリオ。",
    "project.noDescription":"コードと実装の詳細はPublicリポジトリで確認できます。","project.result":"結果","project.currentState":"状態","project.repositories":"リポジトリ","projects.apiFallback":"GitHubに接続できないため、保存済みのPublicプロジェクト一覧を表示しています。","status.prototype":"プロトタイプ","status.learning":"学習プロジェクト","status.planned":"準備中","content.article":"技術記事","content.caseStudy":"ケーススタディ","content.relatedProject":"関連プロジェクト →","nav.insights":"技術記事・事例","section.insights":"技術記事・ケーススタディ","career.clientWeb":"企業Webサイトの企画・WordPress制作・レスポンシブ対応・SEO整備を担当（守秘義務により社名非公開）","career.clientLabel":"実務","career.clientWebPrice":"企業Webサイトの企画・WordPress制作・SEO整備（案件規模：¥300,000＋税）","career.viewAll":"学歴・国際学習歴・全資格を見る →","certifications.selected":"主な資格・学習歴","skills.alsoWorking":"その他の使用技術：","skills.creativeBackground":"クリエイティブ経験：","about.creative":"写真、映像、コピーライティングなどの制作経験を、Webの情報設計とビジュアル表現に活かしています。","about.personalWork":"個人作品 → koshijpn.com","details.projectsTitle":"プロジェクト詳細","details.projectsIntro":"代表プロジェクトの目的、担当、結果、現在の状態、技術、公開リポジトリを掲載しています。","details.publicOnly":"GitHub APIからPublicリポジトリのみを表示します。","details.profileTitle":"学歴・国際学習歴・資格","details.profileIntro":"トップページから分離した経歴と学習記録です。証明書リンクは公開していません。","details.projectsMeta":"プロジェクト詳細 | Koshi Developer Portfolio","details.profileMeta":"学歴・資格 | Koshi Developer Portfolio","github.lead":"ソースコード、実験、継続中の開発をGitHubで管理しています。","github.body":"公開リポジトリでは、実装内容、プロジェクト構成、開発履歴を確認できます。","github.cta":"GitHubプロフィールを見る","contact.lead":"一緒に、役立つものをつくりませんか。","contact.body":"技術的な交流、共同開発、公開コードについてはGitHubへ。Web制作や商用案件についてはSLEEP LATE LABへご相談ください。","contact.githubCta":"GitHubを見る","contact.commercialCta":"商用プロジェクトを相談する"
  },
  "zh-TW": {
    "nav.home":"首頁","nav.about":"關於我","nav.career":"學歷與經歷","nav.skills":"技能","nav.certifications":"資格與學習","nav.featured":"精選專案","nav.otherProjects":"其他專案","nav.experiments":"實驗原型","nav.github":"GitHub","nav.contact":"聯絡","language.label":"語言",
    "hero.eyebrow":"開發者 / 工程師","hero.title":"跨越語言與國界，打造實用的網路產品。","hero.copy":"為日本、台灣與亞洲的多語言社群，企劃、設計並開發簡單易用的網路產品。","hero.projects":"查看專案","section.about":"關於我","section.career":"學歷與經歷","section.skills":"技能","section.certifications":"資格、認證與學習經歷","section.featured":"精選專案","section.otherProjects":"其他專案","section.experiments":"實驗原型","section.contact":"聯絡",
    "about.lead":"主要在日本與台灣活動，專注於多語言網頁開發與獨立產品。","about.body":"結合在多個國家學習的經驗，獨立完成企劃、設計、實作與發布。將WordPress、前後端開發、API、SEO與響應式設計，結合語言、旅行、教育、攝影、影片與文案知識。","about.focusLabel":"專長","about.focus":"網頁開發、WordPress、獨立產品","about.locationLabel":"地點","about.location":"日本 / 台灣・遠端","about.languagesLabel":"語言","about.languages":"日語、英語、華語、泰語",
    "career.1997":"出生於日本北海道","career.2013a":"完成 University of the Visayas ESL課程","career.2013b":"畢業於飛鳥未來高等學校","career.2017":"曾於 Emporia State University 主修傳播學","career.2018":"完成中國文化大學華語中心課程","career.2019":"曾於國立臺灣師範大學主修資訊工程","career.2020a":"完成清邁職業訓練學校皮革課程","career.2020b":"完成清邁大學泰語與文化課程","career.2020c":"完成 Web Courses Bangkok 網頁專業與攝影課程","career.2021":"成立 Sleep Late Lab","career.2022a":"開始銷售 Sleep Late Lab 皮革製品","career.2022b":"完成 Seoul Korean Language Academy Level A2","career.2023a":"完成 NEXT Academy 全端網頁開發課程","career.2023b":"完成 Gold Sounds Academy DJ Course","career.2024":"畢業於大手前大學，取得學術學士／心理學主修","career.2026a":"預計畢業於北海道情報大學","career.2026b":"於文藻外語大學華語中心完成四期華語課程，並完成校內最高級別","career.2026c":"預計入學文藻外語大學國際企業管理系碩士班",
    "skills.usedIn":"使用專案","certifications.intro":"整理資格、認證、獲獎與已完成課程；不公開證明文件連結。","certifications.languages":"語言學習","certifications.education":"心理、教育與社會","certifications.technology":"IT與開發","certifications.health":"健康與體適能","certifications.creative":"藝術、設計與媒體","certifications.other":"其他資格與學習經歷",
    "projects.intro":"依實用性、完成度與技術特色選出的代表專案。","nav.career":"經歷","section.career":"學歷、實務與學習經歷","career.education":"學歷","career.professional":"實務與專案","career.international":"查看國際學習經歷","career.2026a":"目前就讀北海道情報大學，持續修課以完成學位","project.purpose":"目的","project.role":"負責範圍","project.tech":"使用技術","status.caseStudy":"案例研究","status.active":"營運中","skills.experience":"經驗","skills.evidence":"依據","certifications.viewAll":"查看全部資格與學習經歷","a11y.scrollProjects":"前往精選專案","section.beyond":"程式之外","beyond.body":"將攝影、影片、文案與獨立品牌經驗運用於網頁資訊架構與視覺表達。","contact.available":"可承接項目","contact.web":"網頁開發","contact.static":"靜態網站製作","contact.wordpress":"WordPress移轉","contact.multilingual":"多語言內容","contact.collaboration":"技術合作","project.jobs":"由 Svelte 前端與容器化後端組成的全端求職平台。","project.ecommerce":"以前後端分離方式建立的電子商務應用程式。","project.luno":"即時比較 Binance 與 Luno 的比特幣價格並計算溢價。","project.email":"使用 Node.js、Nodemailer 與 IMAP 監控信箱並自動回覆。","project.portfolio":"不使用框架、為 GitHub Pages 建立的多語言響應式作品集。",
    "experiments.intro":"用來探索介面、資料結構與多語言想法的小型原型。","skills.primary":"主要技能","skills.working":"實作經驗","skills.creative":"創意製作","project.technologies":"使用技術","project.github":"GitHub","project.demo":"展示","project.noDescription":"說明準備中。","project.notSpecified":"未指定","project.updated":"更新","projects.loading":"正在從GitHub載入Public儲存庫…","projects.empty":"目前沒有可顯示的Public儲存庫。","projects.error":"無法載入Public儲存庫，請前往GitHub個人頁面查看。","status.public":"公開","status.archived":"已封存","language.full":"完整翻譯","language.partial":"部分翻譯","a11y.skip":"跳至主要內容","a11y.home":"Koshi作品集首頁","a11y.openMenu":"開啟選單","a11y.closeMenu":"關閉選單","a11y.navigation":"主要導覽","a11y.logoAlt":"Koshi標誌","a11y.scrollAbout":"前往關於我","a11y.portraitAlt":"菅原鴻志的個人照片","a11y.backTop":"返回頁首","meta.title":"Koshi | 多語言網頁開發者作品集","meta.description":"菅原鴻志的技術作品集，為日本、台灣與亞洲多語言社群開發實用的網路產品。",
    "project.noDescription":"可在Public儲存庫查看程式碼與實作細節。","project.result":"成果","project.currentState":"狀態","project.repositories":"程式碼儲存庫","projects.apiFallback":"目前無法連線GitHub，正在顯示本機保存的Public專案列表。","status.prototype":"原型","status.learning":"學習專案","status.planned":"準備中","content.article":"技術文章","content.caseStudy":"案例研究","content.relatedProject":"相關專案 →","nav.insights":"技術文章・案例","section.insights":"技術文章與案例研究","career.clientWeb":"負責企業網站企劃、WordPress製作、響應式介面與SEO（依保密義務不公開客戶名稱）","career.clientLabel":"客戶專案","career.clientWebPrice":"企業網站企劃、WordPress製作與SEO（專案規模：日圓300,000未稅）","career.viewAll":"查看全部學歷、國際學習與資格 →","certifications.selected":"精選資格與學習經歷","skills.alsoWorking":"亦使用：","skills.creativeBackground":"創意背景：","about.creative":"將攝影、影片與文案經驗運用於網頁資訊架構及視覺溝通。","about.personalWork":"個人作品 → koshijpn.com","details.projectsTitle":"專案詳情","details.projectsIntro":"整理代表專案的目的、負責範圍、成果、目前狀態、技術與公開儲存庫。","details.publicOnly":"僅從GitHub API載入Public儲存庫。","details.profileTitle":"學歷、國際學習與資格","details.profileIntro":"從首頁移出的詳細學歷與學習紀錄；不公開證明文件連結。","details.projectsMeta":"專案詳情 | Koshi Developer Portfolio","details.profileMeta":"學歷與資格 | Koshi Developer Portfolio","github.lead":"程式碼、實驗與持續開發內容都在GitHub管理。","github.body":"可在公開儲存庫查看實作細節、專案結構與開發紀錄。","github.cta":"查看 GitHub 個人頁面","contact.lead":"一起打造實用的產品。","contact.body":"技術交流、共同開發與公開程式碼請前往GitHub；網站製作與商業專案請聯絡SLEEP LATE LAB。","contact.githubCta":"查看GitHub","contact.commercialCta":"諮詢商業專案"
  },
  "zh-CN": {"nav.home":"首页","nav.about":"关于我","nav.skills":"技能","nav.featured":"精选项目","nav.otherProjects":"其他项目","nav.github":"GitHub","nav.contact":"联系","language.label":"语言","hero.eyebrow":"开发者 / 工程师","hero.title":"打造实用的网络体验。","hero.copy":"从界面到部署，设计并开发无障碍网站与实用的网络应用。","hero.projects":"查看项目","section.about":"关于我","section.skills":"技能","section.featured":"精选项目","section.otherProjects":"其他项目","section.contact":"联系"},
  ko: {"nav.home":"홈","nav.about":"소개","nav.skills":"기술","nav.featured":"주요 프로젝트","nav.otherProjects":"기타 프로젝트","nav.github":"GitHub","nav.contact":"연락처","language.label":"언어","hero.eyebrow":"개발자 / 엔지니어","hero.title":"웹을 위한 유용한 경험을 만듭니다.","hero.copy":"인터페이스부터 배포까지 접근성 높은 웹사이트와 실용적인 웹 앱을 개발합니다.","hero.projects":"프로젝트 보기","section.about":"소개","section.skills":"기술","section.featured":"주요 프로젝트","section.otherProjects":"기타 프로젝트","section.contact":"연락처"},
  th: {"nav.home":"หน้าแรก","nav.about":"เกี่ยวกับ","nav.skills":"ทักษะ","nav.featured":"โปรเจกต์เด่น","nav.otherProjects":"โปรเจกต์อื่น","nav.github":"GitHub","nav.contact":"ติดต่อ","language.label":"ภาษา","hero.eyebrow":"นักพัฒนา / วิศวกร","hero.title":"สร้างประสบการณ์เว็บที่เป็นประโยชน์","hero.copy":"ออกแบบและพัฒนาเว็บไซต์ที่เข้าถึงได้และเว็บแอปที่ใช้งานจริง ตั้งแต่อินเทอร์เฟซจนถึงการเผยแพร่","hero.projects":"ดูโปรเจกต์","section.about":"เกี่ยวกับ","section.skills":"ทักษะ","section.featured":"โปรเจกต์เด่น","section.otherProjects":"โปรเจกต์อื่น","section.contact":"ติดต่อ"},
  vi: {"nav.home":"Trang chủ","nav.about":"Giới thiệu","nav.skills":"Kỹ năng","nav.featured":"Dự án nổi bật","nav.otherProjects":"Dự án khác","nav.github":"GitHub","nav.contact":"Liên hệ","language.label":"Ngôn ngữ","hero.eyebrow":"Lập trình viên / Kỹ sư","hero.title":"Xây dựng trải nghiệm web hữu ích.","hero.copy":"Thiết kế và phát triển website dễ tiếp cận và ứng dụng web thực tế, từ giao diện đến triển khai.","hero.projects":"Xem dự án","section.about":"Giới thiệu","section.skills":"Kỹ năng","section.featured":"Dự án nổi bật","section.otherProjects":"Dự án khác","section.contact":"Liên hệ"},
  es: {"nav.home":"Inicio","nav.about":"Acerca de","nav.skills":"Habilidades","nav.featured":"Proyectos destacados","nav.otherProjects":"Otros proyectos","nav.github":"GitHub","nav.contact":"Contacto","language.label":"Idioma","hero.eyebrow":"Desarrollador / Ingeniero","hero.title":"Creando experiencias útiles para la web.","hero.copy":"Diseño y desarrollo sitios accesibles y aplicaciones web prácticas, desde la interfaz hasta el despliegue.","hero.projects":"Ver proyectos","section.about":"Acerca de","section.skills":"Habilidades","section.featured":"Proyectos destacados","section.otherProjects":"Otros proyectos","section.contact":"Contacto"}
};

Object.assign(translations.en, {
  "hero.eyebrow":"Multilingual Web Developer","hero.line1":"Static Websites.","hero.line2":"AI-assisted Workflows.","hero.line3":"Multilingual Products.","hero.tagsLabel":"Core technologies","hero.statCommercial":"Commercial web project · before tax","hero.statFounded":"Founded SLEEP LATE LAB","hero.statRemote":"Remote collaboration",
  "about.lead":"I work mainly between Japan and Taiwan on multilingual web development and independent products.","about.body":"Drawing on experience studying in several countries, I handle planning, information architecture, implementation, and release. My focus is static sites, WordPress, front-end development, API integration, and SEO, supported by experience in photography, video, and copywriting.",
  "commercial.eyebrow":"Selected Commercial Work","commercial.title":"Corporate Website","commercial.visibility":"Client name withheld","commercial.value":"Project Value","commercial.delivery":"Delivery","commercial.scope":"Planning, production, and launch","commercial.tagPlanning":"Planning","commercial.tagResponsive":"Responsive Design",
  "github.loading":"Loading public GitHub data…","github.publicRepos":"Public repositories","github.languages":"Primary languages","github.latestActivity":"Latest public repository update","github.lastSynced":"Last synced","github.recent":"Recently updated","github.latestCommit":"Latest commit","github.fallback":"GitHub data is temporarily unavailable. View current public repositories on the GitHub profile.",
  "contact.replyLabel":"Typical reply","contact.reply":"Usually within 2–3 business days","contact.modeLabel":"Collaboration","contact.mode":"Remote","contact.regionLabel":"Regions","contact.region":"Japan · Taiwan · Worldwide",
  "status.client":"Client Work","status.legacy":"Legacy","project.year":"Year","details.projectsIntro":"Development work across client websites, WordPress, static sites, APIs, private projects and public repositories.","details.publicOnly":"Additional Public repositories are loaded from the GitHub API. Commercial inquiries are handled by SLEEP LATE LAB."
});
Object.assign(translations.ja, {
  "hero.eyebrow":"多言語Web開発者","hero.line1":"静的Webサイト。","hero.line2":"AI支援ワークフロー。","hero.line3":"多言語プロダクト。","hero.copy":"日本・台湾・アジアをつなぐ、実用的なデジタルプロダクトを設計・開発しています。","hero.tagsLabel":"主な技術","hero.statCommercial":"商用Web案件・税別","hero.statFounded":"SLEEP LATE LAB設立","hero.statRemote":"リモート対応",
  "about.lead":"日本と台湾を中心に、多言語Web開発と個人開発に取り組んでいます。","about.body":"複数の国で学んだ経験を活かし、企画、情報設計、実装、公開まで一貫して担当します。静的サイト、WordPress、フロントエンド、API連携、SEOを中心に、写真・映像・コピーライティングの経験をWebの表現とユーザー体験に活かしています。",
  "commercial.eyebrow":"主な商用実績","commercial.title":"企業Webサイト","commercial.visibility":"クライアント名非公開","commercial.value":"案件規模","commercial.delivery":"対応範囲","commercial.scope":"企画・制作・公開対応","commercial.tagPlanning":"企画","commercial.tagResponsive":"レスポンシブ",
  "github.loading":"GitHubの公開データを読み込んでいます…","github.publicRepos":"Publicリポジトリ","github.languages":"主要言語","github.latestActivity":"最新のPublicリポジトリ更新","github.lastSynced":"最終同期","github.recent":"最近更新されたリポジトリ","github.latestCommit":"最新コミット","github.fallback":"GitHubの公開データを一時的に取得できません。最新情報はGitHubプロフィールで確認できます。",
  "contact.replyLabel":"返信目安","contact.reply":"通常2〜3営業日以内","contact.modeLabel":"対応形式","contact.mode":"リモート協業","contact.regionLabel":"対応地域","contact.region":"日本・台湾・Worldwide",
  "status.client":"クライアント案件","status.legacy":"旧サイト","project.year":"制作年","details.projectsIntro":"クライアントサイト、WordPress、静的サイト、API、Private案件、公開リポジトリを含む開発実績です。","details.publicOnly":"追加のPublicリポジトリはGitHub APIから取得します。商用案件のご相談はSLEEP LATE LABで受け付けています。"
});
Object.assign(translations["zh-TW"], {
  "hero.eyebrow":"多語言網頁開發者","hero.line1":"靜態網站。","hero.line2":"AI輔助工作流程。","hero.line3":"多語言產品。","hero.copy":"設計並開發連結日本、台灣與亞洲的實用數位產品。","hero.tagsLabel":"核心技術","hero.statCommercial":"商業網站專案・未稅","hero.statFounded":"成立SLEEP LATE LAB","hero.statRemote":"遠端合作",
  "about.lead":"以日本與台灣為主要活動據點，投入多語言網站開發與個人產品。","about.body":"運用在多個國家學習的經驗，從企劃、資訊架構、實作到發布皆可一貫負責。以靜態網站、WordPress、前端開發、API整合與SEO為核心，並將攝影、影片與文案經驗運用於網站表現和使用者體驗。",
  "commercial.eyebrow":"精選商業實績","commercial.title":"企業網站","commercial.visibility":"客戶名稱不公開","commercial.value":"專案規模","commercial.delivery":"交付範圍","commercial.scope":"企劃、製作與發布","commercial.tagPlanning":"企劃","commercial.tagResponsive":"響應式設計",
  "github.loading":"正在載入GitHub公開資料…","github.publicRepos":"Public儲存庫","github.languages":"主要語言","github.latestActivity":"最新Public儲存庫更新","github.lastSynced":"最後同步","github.recent":"最近更新","github.latestCommit":"最新提交","github.fallback":"目前暫時無法取得GitHub公開資料；最新資訊請前往GitHub個人頁面查看。",
  "contact.replyLabel":"通常回覆","contact.reply":"通常2至3個工作天內","contact.modeLabel":"合作形式","contact.mode":"遠端合作","contact.regionLabel":"服務地區","contact.region":"日本・台灣・全球",
  "status.client":"客戶專案","status.legacy":"舊網站","project.year":"製作年份","details.projectsIntro":"收錄客戶網站、WordPress、靜態網站、API、Private 專案與公開儲存庫等開發實績。","details.publicOnly":"其他 Public 儲存庫由 GitHub API 載入；商業專案請聯絡 SLEEP LATE LAB。"
});

let currentLanguage = "ja";
function getTranslation(key) { return translations[currentLanguage]?.[key] || translations.en[key] || key; }
function getCurrentLanguage() { return currentLanguage; }

function changeLanguage(language) {
  currentLanguage = translations[language] ? language : "en";
  document.documentElement.lang = currentLanguage;
  localStorage.setItem("preferredLanguage", currentLanguage);
  document.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = getTranslation(element.dataset.i18n); });
  document.querySelectorAll("[data-i18n-aria-label]").forEach((element) => { element.setAttribute("aria-label", getTranslation(element.dataset.i18nAriaLabel)); });
  document.querySelectorAll("[data-i18n-alt]").forEach((element) => { element.alt = getTranslation(element.dataset.i18nAlt); });
  document.querySelectorAll("[data-i18n-label]").forEach((element) => { element.label = getTranslation(element.dataset.i18nLabel); });
  const page = document.body.dataset.page;
  const titleKey = page === "projects" ? "details.projectsMeta" : page === "profile" ? "details.profileMeta" : "meta.title";
  document.title = getTranslation(titleKey);
  const description = document.querySelector('meta[name="description"]');
  if (description && page === "home") description.content = getTranslation("meta.description");
  document.querySelectorAll('meta[property="og:title"], meta[name="twitter:title"]').forEach((element) => { element.content = getTranslation(titleKey); });
  document.querySelectorAll('meta[property="og:description"], meta[name="twitter:description"]').forEach((element) => { element.content = getTranslation("meta.description"); });
  const selector = document.getElementById("language-select");
  if (selector) selector.value = currentLanguage;
  document.dispatchEvent(new CustomEvent("languagechange", { detail: currentLanguage }));
}

window.getTranslation = getTranslation;
window.getCurrentLanguage = getCurrentLanguage;
window.changeLanguage = changeLanguage;

document.addEventListener("DOMContentLoaded", () => {
  const saved = localStorage.getItem("preferredLanguage");
  const initial = saved && translations[saved] ? saved : "ja";
  changeLanguage(initial);
  document.getElementById("language-select")?.addEventListener("change", (event) => changeLanguage(event.target.value));
});
